### ISSUE TITLE
[components] custom training job from component bug

### ISSUE THREAD

**Issue by wardVD** [kubeflow/pipelines#7234] opened 2022-01-31 12:30 UTC
### Environment

*  KFP version:
kfp==1.8.10
*  google_cloud_pipeline_components SDK version: 
google-cloud-pipeline-components==0.2.2

### Steps to reproduce

1) create a python function based component, e.g.:
```
@component
def process(
    output_dataset_one: Output[Dataset],
):
    output_dataset_one.metadata["hello"] = "there"
```
2) import custom job utils in pipeline code:
```
from google_cloud_pipeline_components.experimental.custom_job import utils as custom_job_utils
```
Transform component into training job:

```
process_op = custom_job_utils.create_custom_training_job_op_from_component(
    process,
    display_name = 'test-component',
    machine_type = 'n1-standard-4',
    boot_disk_type = 'pd-ssd',
    boot_disk_size_gb = "150"
    )
```

3) Run pipeline:

```
@dsl.pipeline(
    name='test',
    description="Pipeline to test custom training job component"
)
def test_pipeline():
    _ = (
        process_op(
            project=<PROJECT_ID>,
            location=<REGION>,
        )
        .set_display_name('test')
    )
```

### Expected result

The artifact`output_dataset_one` will have a property/metadata `hello` if component is run normally, but when the component is transformed into a custom training job, the resulting artifact will not contain any properties/metadata. This seems like a bug.

### Materials and Reference

https://github.com/kubeflow/pipelines/blob/master/components/google-cloud/google_cloud_pipeline_components/experimental/custom_job/utils.py
---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by venkatagedda** [comment] 2022-02-03 11:16
Having same issue it is not able to print the log_metric also

**Comment by rui5i** [comment] 2022-02-07 23:49
Reproduced the issue and looks like the `executor_output.json` is not generated which is causing the problem.

**Comment by IronPan** [comment] 2022-02-15 01:37
This affects also the output parameters

**Comment by IronPan** [comment] 2022-04-18 17:25
This is now fixed, and the output is emitted as expected. Please reopen if this still happens.

**Closed by IronPan** 2022-04-18 17:25 UTC
Labels: kind/bug, area/sdk

**Comment by psc-dlt** [comment] 2023-01-05 10:42
@IronPan still not able to use log_metric(), any suggestion?
