### ISSUE TITLE
HTTP response body: OpenID Connect token expired: JWT has expired

### ISSUE THREAD

**Issue by wanglong001** [kubeflow/pipelines#5145] opened 2021-02-18 06:34 UTC
### What steps did you take:
1.  gcloud auth activate-service-account account --key-file=...
2. copy credentials.json  ~/.config/kfp/
3. Client is a singleton: kfp.Client(host=KUBEFLOW_AUTHORIZATION.HOST,
                                                client_id=KUBEFLOW_AUTHORIZATION.CLIENT_ID,
                                                other_client_id=KUBEFLOW_AUTHORIZATION.OTHER_CLIENT_ID,
                                                other_client_secret=KUBEFLOW_AUTHORIZATION.OTHER_CLIENT_SECRET)
4. after a few days, this problem occurred

### What happened:
![image](https://user-images.githubusercontent.com/14817376/108314396-ca01b300-71f4-11eb-9161-5aa71dcbd1aa.png)

### What did you expect to happen:
![image](https://user-images.githubusercontent.com/14817376/108314716-514f2680-71f5-11eb-8f3a-4d647ad72a3b.png)
_is_refresh_token = True, The token should be refreshed automatically, but JWT has expired.

### Environment:
_**client:**_
      ubuntu18.06
      kfp                      1.4.0
      kfp-pipeline-spec        0.1.5
      kfp-server-api           1.3.0
      Python 3.7.7
_**service:**_
      google cloud

**Comment by Bobgy** [comment] 2021-03-12 01:06
Duplicate of https://github.com/kubeflow/pipelines/issues/4321

**Closed by Bobgy** 2021-03-12 01:07 UTC
