### ISSUE TITLE
Frontend UI takes long to render the page

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/pipelines#3165] opened 2020-02-24 22:08 UTC
### What steps did you take:
Randomly click pipeline and experiments tab. 

### What happened:

It's pretty slow and seems calls didn't come into pipeline backend because there's no logs. 
![image](https://user-images.githubusercontent.com/4739316/75195508-ec124380-570e-11ea-8962-3d9307c3c6a3.png)

After half minutes. I get result returned. 

![image](https://user-images.githubusercontent.com/4739316/75195690-46130900-570f-11ea-83f2-fdb2d49769c9.png)

I am wondering if some GCP specific `project-id` or `cluster-name` has impact on normal pipeline calls like `/experiments?page=...`

### What did you expect to happen:
Webpage should have a quick response. 

### Environment:

KFP version: 0.2.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/area frontend

**Comment by Bobgy** [comment] 2020-02-25 08:19
@Jeffwan the issue seems a duplicate of https://github.com/kubeflow/pipelines/issues/3070.
Did you try ml-pipeline-ui 0.2.4? It should mitigate the most and you can further reduce the impact by https://github.com/kubeflow/pipelines/issues/3070#issuecomment-588978533

**Comment by Jeffwan** [comment] 2020-02-25 18:33
@Bobgy Sure. Let me have a try. In v1.0 release, we are still using 0.2.0? Any chance to bump up the version if there're lots of improvement there.

**Comment by Bobgy** [comment] 2020-02-26 03:04
This might be a good enough reason to bump, I will sync with @jlewi about this.

**Comment by Bobgy** [comment] 2020-03-22 09:03
/close
Because this is no longer a problem with KFP, will track in https://github.com/kubeflow/manifests/issues/984

**Closed by Bobgy** 2020-03-22 09:03 UTC
Labels: area/frontend, kind/bug, needs investigation, status/triaged

**Comment by niteshldd** [comment] 2020-04-27 18:18
Hi Team,

We are having same issue even we are using latest version.

**Comment by Bobgy** [comment] 2020-04-28 00:17
@niteshldd Can you look At network panel? which requests are there?
Also, what is the version you are using?

**Comment by niteshldd** [comment] 2020-04-28 05:58
![image](https://user-images.githubusercontent.com/36432860/80451642-f97fc000-8941-11ea-995e-5cc629e0ec97.png)

Hi 

Please find the attached screenshot,

We are using  kubeflow version - V1.0

**Comment by Bobgy** [comment] 2020-04-28 07:04
@niteshldd Thanks for the screenshot. Can you open a separate issue with details? This seems different from this report.

Problems in this issue are requests of `project-id` and `cluster-name` are stuck.
