### ISSUE TITLE
GCP components do not seem to work with workflow identity when the default SA is deleted

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#3908] opened 2020-06-04 00:55 UTC

**Comment by rmgogogo** [comment] 2020-06-05 09:09
hi Alexey, for saving Hongye bandwidth, feel free to assign to me.

Quick question: which component here you mean? Or all GCP components?

**Comment by Ark-kun** [comment] 2020-06-08 01:35
> Quick question: which component here you mean? Or all GCP components?

I've seen this affecting `gcp/dataproc/create_cluster` component, but it might be affecting all gcp components since they use the same client instantiation code.

**Comment by Bobgy** [comment] 2020-06-08 02:44
@Ark-kun Can you clarify, which default SA was deleted? The compute-xxxxxx@... default GSA?

**Comment by rmgogogo** [comment] 2020-06-22 07:15
(as detailed in email, we may close as the root cause is that WI is not well configured)

**Closed by rmgogogo** 2020-06-22 07:15 UTC
Labels: area/components, kind/bug, status/triaged
