### ISSUE TITLE
mlpipeline-metrics not found

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/pipelines#3164] opened 2020-02-24 22:00 UTC
### What steps did you take:
I just install v1.0 and kick off Exit-Handler pipeline. 

### What happened:

Checking pipeline logs, I get
```
I0224 21:55:00.245907       1 interceptor.go:29] /api.RunService/ReadArtifact handler starting
I0224 21:55:00.248584       1 error.go:218] ResourceNotFoundError: artifact runs/9c61556e-8ba8-4ad1-b579-639678a0abd8/nodes/exit-handler-mc8v6/artifacts/mlpipeline-metrics not found.
github.com/kubeflow/pipelines/backend/src/common/util.NewResourceNotFoundError
	backend/src/common/util/error.go:150
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).ReadArtifact
	backend/src/apiserver/resource/resource_manager.go:860
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ReadArtifact
	backend/src/apiserver/server/run_server.go:134
github.com/kubeflow/pipelines/backend/api/go_client._RunService_ReadArtifact_Handler.func1
	bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1395
main.apiServerInterceptor
	backend/src/apiserver/interceptor.go:30
github.com/kubeflow/pipelines/backend/api/go_client._RunService_ReadArtifact_Handler
	bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1397
google.golang.org/grpc.(*Server).processUnaryRPC
	external/org_golang_google_grpc/server.go:966
google.golang.org/grpc.(*Server).handleStream
	external/org_golang_google_grpc/server.go:1245
google.golang.org/grpc.(*Server).serveStreams.func1.1
	external/org_golang_google_grpc/server.go:685
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1333
failed to read artifact 'run_id:"9c61556e-8ba8-4ad1-b579-639678a0abd8" node_id:"exit-handler-mc8v6" artifact_name:"mlpipeline-metrics" '.
github.com/kubeflow/pipelines/backend/src/common/util.(*UserError).wrapf
	backend/src/common/util/error.go:206
github.com/kubeflow/pipelines/backend/src/common/util.Wrapf
	backend/src/common/util/error.go:231
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ReadArtifact
	backend/src/apiserver/server/run_server.go:137
github.com/kubeflow/pipelines/backend/api/go_client._RunService_ReadArtifact_Handler.func1
	bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1395
main.apiServerInterceptor
	backend/src/apiserver/interceptor.go:30
github.com/kubeflow/pipelines/backend/api/go_client._RunService_ReadArtifact_Handler
	bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1397
google.golang.org/grpc.(*Server).processUnaryRPC
	external/org_golang_google_grpc/server.go:966
google.golang.org/grpc.(*Server).handleStream
	external/org_golang_google_grpc/server.go:1245
google.golang.org/grpc.(*Server).serveStreams.func1.1
	external/org_golang_google_grpc/server.go:685
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1333
/api.RunService/ReadArtifact call failed
github.com/kubeflow/pipelines/backend/src/common/util.(*UserError).wrapf
	backend/src/common/util/error.go:206
github.com/kubeflow/pipelines/backend/src/common/util.Wrapf
	backend/src/common/util/error.go:231
main.apiServerInterceptor
	backend/src/apiserver/interceptor.go:32
github.com/kubeflow/pipelines/backend/api/go_client._RunService_ReadArtifact_Handler
	bazel-out/k8-opt/bin/backend/api/linux_amd64_stripped/go_client_go_proto%/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:1397
google.golang.org/grpc.(*Server).processUnaryRPC
	external/org_golang_google_grpc/server.go:966
google.golang.org/grpc.(*Server).handleStream
	external/org_golang_google_grpc/server.go:1245
google.golang.org/grpc.(*Server).serveStreams.func1.1
	external/org_golang_google_grpc/server.go:685
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1333
``` 
![image](https://user-images.githubusercontent.com/4739316/75194905-d6504e80-570d-11ea-977f-885605d40bbd.png)

### What did you expect to happen:
It suppose to have a `run/` in minio bucket. 

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
using kfctl

KFP version: 0.2.0 docker-pullable://gcr.io/ml-pipeline/api-server@sha256:8149af1522a5fd75292dcb8630840dc23541d8c22f6d6938d3f45b6fd759872e

KFP SDK version: n/a

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug
/area backend

**Comment by Ark-kun** [comment] 2020-02-26 07:20
Did you run a preloaded pipeline or did you compile/submit it yourself?

**Comment by shotarohorai** [comment] 2020-02-26 17:08
I got the same error. It is emitted constantly.

In my case, I compile and submit runs by myself.

**Comment by Jeffwan** [comment] 2020-02-26 23:09
> Did you run a preloaded pipeline or did you compile/submit it yourself?

I use preload pipeline `exit-handler` the first one.  I create a run on pipeline ui.

**Comment by Bobgy** [comment] 2020-02-27 07:21
Also
/assign @jingzhang36

**Comment by Bobgy** [comment] 2020-02-27 07:22
@jingzhang36 this looks like a blocking issue, would you mind taking a look?

**Comment by Bobgy** [comment] 2020-03-03 12:11
Just confirmation, were there any errors in the pipeline log? Did it download data successfully?

And is this a duplicate of https://github.com/kubeflow/kubeflow/issues/4803?

**Comment by jonasdebeukelaer** [comment] 2020-05-14 10:51
Not sure where this is at, but I started getting these error logs if I used a non-existent service account for a run. 
The only way to make it stop was to delete the run (using proxy to api)

**Comment by Bobgy** [comment] 2020-05-15 01:49
Sounds like persistence agent is causing these, it keeps asking api-server to sync old workflows even when they have finished.
/cc @jingzhang36 @IronPan 

We have get a fix to this.

@jonasdebeukelaer Yes, I think your case is the same, as long as there's a workflow that declares some artifact, but it wasn't generated. This error will show up.

**Comment by Bobgy** [comment] 2020-05-15 01:50
Does it work for you if api-server just log this as an info, instead of error? It warns about data, but it's valid data is missing some times (when there is a user error)

**Comment by jonasdebeukelaer** [comment] 2020-05-15 10:28
@Bobgy not sure if that question is for me, but yeah would be fine for me, I was just testing that changing service accounts works in a feature I'm working on. So long as it's a little more succinct 😄

**Comment by jingzhang36** [comment] 2020-05-18 23:41
Seems duplicate of https://github.com/kubeflow/pipelines/issues/3699

**Comment by Bobgy** [comment] 2020-05-19 00:49
@jingzhang36 yes, let's use #3699 to track it
/close
Duplicates #3699

**Closed by Bobgy** 2020-05-19 00:49 UTC
Labels: area/backend, kind/bug, priority/p0, status/triaged
