### ISSUE TITLE
Error getting logs

### ISSUE THREAD

**Issue by lluunn** [kubeflow/pipelines#290] opened 2018-11-15 22:00 UTC
I ran the sample Condition pipeline, and it successfully finished.
But when I clicked on the steps, most of them are not able to get logs.

<img width="1031" alt="screen shot 2018-11-15 at 13 56 05" src="https://user-images.githubusercontent.com/32310205/48584459-9d0c1a80-e8de-11e8-82d6-7e9bc5e662ef.png">

**Comment by yebrahim** [comment] 2018-11-19 20:05
Does this pod exist in the cluster? Can you try running `kubectl get pod -n kubeflow <pod-name>` in a shell? It could have been that the pod has been removed by resizing the cluster, or by manually deleting the job/pod.

**Comment by rileyjbauer** [comment] 2018-12-14 19:47
If this is what @yebrahim mentioned, then it's likely a duplicate of #93

**Comment by yebrahim** [comment] 2019-01-03 07:43
Closing for no activity.
/close

**Closed by yebrahim** 2019-01-03 07:43 UTC
