### ISSUE TITLE
Half of the UI is cut off in Firefox

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1572] opened 2019-06-28 08:06 UTC
During the customer meeting they tried to use Firefox to access the UI. Lower part of the UI was hidden/obscured/unavailable.
@rileyjbauer Can you please check the latest UX version on Firefox?

**Comment by rileyjbauer** [comment] 2019-07-10 23:11
I'm not seeing this, though I am seeing CORS-related issues when trying to call the KFP APIs. Requests are being rerouted to `https://accounts.google.com/o/oauth2/v2/auth` with the redirect URI being something IAP related: `https://iap.googleapis.com/v1/oauth/clientIds/...`

@avdaredevil Do you know if other Kubeflow apps behave properly on Firefox?

**Comment by Bobgy** [comment] 2019-10-29 11:19
Need to verify if firefox works with KFP UI first.

**Comment by Bobgy** [comment] 2019-11-08 09:12
I cannot reproduce the issue @Ark-kun mentioned. @Ark-kun do you have any context with that?

I did reproduce the auth issue @rileyjbauer mentioned above. I identified the root cause: https://github.com/github/fetch#sending-cookies
When sending requests, we should explicitly set `credentials: same-origin`. Chrome and Firefox has different default values on this.

**Comment by Bobgy** [comment] 2019-11-08 09:18
For the half of UI cut off issue, I did see it once when using KFP UI in Kubeflow. Screencastify chrome plugin conflicts with Kubeflow UI. When I try to record videos, the screen is cut off in half. I suspect its a similar issue in this case. Probably some other plugin that inserts an element to the screen interfered with Kubeflow central dashboard.

I'm closing this because I don't think it's related to KFP UI.
Please reopen if you can reproduce.

/close

**Closed by Bobgy** 2019-11-08 09:18 UTC
Labels: kind/bug, priority/p0

**Comment by speaknowpotato** [comment] 2021-12-27 06:55
I had the same issue today and finally found out it was due to some chrome extensions. 
After disabling them, the UI is working fine. 
Thanks @Bobgy .

**Comment by chrisjune** [comment] 2023-09-12 05:43
I am faced same issue using [DeepL extension](https://chrome.google.com/webstore/detail/deepl-translate-reading-w/cofdbpoegempjloogbagkncekinflcnj). 
When I turn this extension it works well.
