### ISSUE TITLE
pip3 install kfp --user or pip install kfp does not set $PATH

### ISSUE THREAD

**Issue by IreneGi** [kubeflow/pipelines#2793] opened 2020-01-03 23:15 UTC
Run pip3 install kfp --user and then kfp says path not found, need to run export PATH=$PATH:~/.local/bin for cli deployment to work

**Comment by numerology** [comment] 2020-01-03 23:23
Hi @IreneGi , do you mind pasting the full error message? Thanks.
For the CLI deployment are you talking about [standalone deployment](https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize)?

**Comment by SinaChavoshi** [comment] 2020-01-03 23:35
This issue happens when you are installing the KFP SDK ... the CLI binary is not in the path after installation..

**Comment by SinaChavoshi** [comment] 2020-01-03 23:45
seems like this is related to https://github.com/pypa/pip/issues/3813

**Comment by SinaChavoshi** [comment] 2020-01-03 23:48
just verified a correct error message is shown at the end of the pip3 install however this is not a good user experience 

```
Installing collected packages: kfp
  The scripts dsl-compile and kfp are installed in '/home/chavoshi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

**Comment by numerology** [comment] 2020-01-04 00:08
Summary of offline discussion:

The actual problem is the linux OS image used by cloud shell does not include $HOME/.local/bin in $PATH, so binaries installed using '--user' option are not runnable. Have issued a feedback to cloud shell team.

We shall also escalate this issue to datalab team

**Comment by SinaChavoshi** [comment] 2020-02-03 20:50
closing as root cause can not be addressed within KFP as described above.

**Closed by SinaChavoshi** 2020-02-03 20:50 UTC
Labels: area/sdk, upstream_issue
