### ISSUE TITLE
when using the emissary executor you must either explicitly specify the command, or list the image's command in the index: https://argoproj.github.io/argo-workflows/workflow-executors/#emissary-emissary[bug] <Bug Name>

### ISSUE THREAD

**Issue by kotalakshman** [kubeflow/pipelines#8240] opened 2022-09-05 12:20 UTC
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)? 

*  KFP version: 1.7.1

*  KFP SDK version:1.7.1
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

### Labels

---

Impacted by this bug? Give it a 👍.

**Comment by kotalakshman** [comment] 2022-09-06 02:58
using kubeflow , machine learning model deployed in to kubernetes,then i'm getting the attached error message

**Comment by zijianjoy** [comment] 2022-09-08 23:04
Hello @kotalakshman ,

There are multiple information in here, I am assuming you are using container component in your pipeline:

1. In the issue title, this is by design because you need to explicitly specify the command in your container spec. Example: https://github.com/kubeflow/pipelines/pull/6143/files
2. In the issue description, you need to start using Python 3 because Python 2 is no longer supported. 

I am closing this issue for now with solutions provided. If you have more questions, feel free to reopen.

**Closed by zijianjoy** 2022-09-08 23:04 UTC
Labels: kind/bug
