### ISSUE TITLE
When notebook submits a run and clicks the link they get "Error: failed to retrieve run:"

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1017] opened 2019-03-22 01:15 UTC
We should make it so that the user does not see the error.
```
Error: failed to retrieve run: 942689da-4c3f-11e9-bdef-42010a8000a2. Click Details for more information.
```

When the run is submitted, the client receives the run ID. So the run entry must already exist in the DB. The Frontend should see that and prevent the error.

**Comment by vicaire** [comment] 2019-03-26 03:01
Could you please provide more details? Why not fixing the error itself for instance?

**Comment by Ark-kun** [comment] 2019-03-26 21:56
> Could you please provide more details? Why not fixing the error itself for instance?

I think that the problem is well-known and reproducible. I'm just adding a tracking item.

**Comment by rileyjbauer** [comment] 2019-03-27 18:01
Does the user only see this error immediately after submitting, or is it always broken?

Are you seeing this error within the web UI?

What is the expected behavior here?

**Comment by Ark-kun** [comment] 2019-03-27 19:52
> Are you seeing this error within the web UI?

Yes.

> Does the user only see this error immediately after submitting, or is it always broken?

The user sees the error immediately after submitting a new run and clicking the Run link.
After a bit of time and several refreshes, the message goes away.
 
> What is the expected behavior here?

I expect not to see this error message when the run exists in the DB.
As a user, I know that the run exists since I have it's ID returned from the backend server which meand that it was inserted into the DB.

Do you know why this error happens? Is this frontend or backend issue?

**Comment by rileyjbauer** [comment] 2019-03-29 02:04
The frontend is indicating that the backend returned an error when the run was requested.]

I tried this with a few different notebooks and was not able to reproduce it. Have you seen it since the auto-refresh feature was added?

**Comment by vicaire** [comment] 2019-04-09 02:17
Resolving, please reopen with the additional details that rileybauer@ requested if the problem is still showing up.

**Closed by vicaire** 2019-04-09 02:17 UTC
Labels: area/front-end, kind/bug, priority/p1

**Comment by Ark-kun** [comment] 2019-04-10 03:18
>I tried this with a few different notebooks and was not able to reproduce it.

I see it almost every time I submit a run from a notebook.

> could you click "Details" when you see the above error and paste what it says here as well? That should indicate what error the backend is sending

AFAIR, the error message was the same ~ "Failed to retrieve run".
