### ISSUE TITLE
Kubeflow / AI Platform Pipelines component visualization missing 

### ISSUE THREAD

**Issue by SaschaHeyer** [kubeflow/pipelines#5302] opened 2021-03-15 13:06 UTC
### What steps did you take:

1. run the pipeline (visualization is rendered)
2. run the pipeline again (visualization is missing)

### What happened:
On the second run, the StatisticsGen component has missing static HTML and metadata.
This issue can be reproduced only if the run output is taken from the cache. 

Runs not taken from cache work as expected.

I assume this is an issue related to the cache. 

<img width="1211" alt="1" src="https://user-images.githubusercontent.com/1991664/111157846-a59cba80-8597-11eb-9d35-b95f77582e09.png">
<img width="1201" alt="11" src="https://user-images.githubusercontent.com/1991664/111157853-a6cde780-8597-11eb-99d0-66fdbac7c6b4.png">

### What did you expect to happen:
The visualization for the TFX StatisticsGen component is rendered

### Environment:
Google AI Platform Pipelines

How did you deploy Kubeflow Pipelines (KFP)?
Using Google AI Platform Pipelines

KFP version: https://github.com/kubeflow/pipelines/commit/d79071c0bef19442483abc101769a0d893e72f42

KFP SDK version: no pip in AI Platform Pipelines

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment] 2021-03-27 00:58
Duplicate of #5303

**Comment by Bobgy** [comment] 2021-03-27 00:58
This has the same root cause, so I am closing it

**Closed by Bobgy** 2021-03-27 00:58 UTC
Labels: kind/bug, priority/p0
