### ISSUE TITLE
[feature] Compare tensorboards output from selected runs

### ISSUE THREAD

**Issue by blacky-i** [kubeflow/pipelines#7476] opened 2022-03-28 11:45 UTC
### Feature Area
/area frontend

### What feature would you like to see?
In kubeflow v1.3 was such feature. On bare metal kubeflow deployment (with local volume mounting for tensorboard, more here [#4208](https://github.com/kubeflow/pipelines/issues/4208)) I had a possibility selected several runs, click compare and in `Metrics` section there was combined tensorboard artifact for viewing. Now this feature apparently removed. 

### What is the use case or pain point?
To be able to view several runs logs simultaniosly in one tensorboard pod

### Is there a workaround currently?
There was, but apparently it is possible only to compare scalar metrics

---

Love this idea? Give it a 👍. We prioritize fulfilling features with the most 👍.

**Comment by pyang-aurora** [comment] 2022-03-29 06:07
@zijianjoy for viz

**Comment by pyang-aurora** [comment] 2022-03-29 06:15
The issue can be reproduced using a locally deployed KFP infra (with minikube), following documentation under `manifests/kustomize`. 
https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize#envplatform-agnostic-install-on-any-kubernetes-cluster

We compiled the following pipeline using the latest KFP SDK 
https://github.com/kubeflow/pipelines/blob/1.8.1/samples/core/visualization/tensorboard_minio.py

```
dsl-compile --py tensorboard_minio.py --output tensorboard_minio_pipeline.yaml
```
For each version of the KFP infra, the generated YAML file was uploaded and two runs were created from it. 

### KFP 1.5.1
![image](https://user-images.githubusercontent.com/86134397/160544451-a7ce63e0-098f-4a65-a2da-53cdff39e772.png)
### KFP 1.7.0
![image](https://user-images.githubusercontent.com/86134397/160544488-166a864b-3369-49c2-8ad8-99a55dd47e14.png)

**Comment by zijianjoy** [comment] 2022-03-29 15:29
Thank you for reporting this bug, can you help me validate that the Tensorboard has disappeared from individual run's visualization too?

On the KFP UI, navigate to `Runs`, select a run with Tensorboard metrics, then click the pipeline step which has Tensorboard metrics on the Pipeline graph. It will open the `side panel` for you, then select `Visualization` to check whether Tensorboard exists. 

For reference, we don't see much change from the comparison page recently: https://github.com/kubeflow/pipelines/blob/master/frontend/src/pages/Compare.tsx

**Comment by zijianjoy** [comment] 2022-03-29 15:29
cc @jiyongjung0

**Comment by blacky-i** [comment] 2022-03-29 15:32
Hello, in individual runs with selected tensorboard output works fine. Viewer created and works fine.  

BTW I am using V1_LEGACY mode for pipeline creation

**Comment by pyang-aurora** [comment] 2022-03-29 16:48
I also tried with `V2_COMPATIBLE` compilation mode and got the same result in KFP 1.7.0. 
![image](https://user-images.githubusercontent.com/86134397/160663826-4e3bda8f-542a-42b8-90d0-7ce8fe863873.png)

**Comment by pyang-aurora** [comment] 2022-03-29 16:53
In both `V1` and `V2_COMPATIBLE` versions, there's no tensorboard in pipeline output page.
![image](https://user-images.githubusercontent.com/86134397/160664435-5856b8a6-8170-45de-b86f-5c7da6cdf199.png)

However tensorboard can be found in the visualization component task
![image](https://user-images.githubusercontent.com/86134397/160664577-ea13903b-8349-4007-aaca-d4a378c3a7b1.png)

**Comment by zijianjoy** [comment] 2022-03-29 17:38
The compare-run page is trying to read `metric` field from ApiRun: https://github.com/kubeflow/pipelines/blob/1c3e2768e6177d5d6e3f4b8eff8fafb9a3b76c1f/frontend/src/lib/RunUtils.ts#L141. However, it is actually a backend change which has switched from ReportMetrics API to use MLMD to store visualization. Because of that, the compare-run page stopped working on metrics visualization. We are going to address this as part of KFPv2 effort, but the functionality will probably stay broken for v1. 


cc @Bobgy to correct me if I made any mistake in the statement.

**Comment by zijianjoy** [comment] 2022-03-29 17:39
cc @chensun for visibility

**Comment by zijianjoy** [comment] 2022-03-29 21:05
I am not super familiar with MetricsReporting part in the backend, I will let @chensun comments on how to support such fix.

**Comment by pyang-aurora** [comment] 2022-08-26 20:29
Any update on this issue?

**Comment by zijianjoy** [comment] 2022-08-30 05:32
Currently we are looking for help to implement this feature on KFPv2.

**Comment by rimolive** [comment] 2024-03-07 15:39
Is this issue still relevant? KFPv2 is out but I don't know if this feature is implemented

**Comment by zijianjoy** [comment] 2024-03-07 19:11
Tensorboard is not going to be supported in KFPv2, I think it is safe to close this issue now.
/close

**Closed by zijianjoy** 2024-03-07 19:11 UTC
Labels: help wanted, area/frontend, kind/feature
