### ISSUE TITLE
Tests are launched in doubles since Nov 09 18:30

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#197] opened 2018-11-10 11:22 UTC
See https://prow.k8s.io/?repo=kubeflow%2Fpipelines&job=presubmit-e2e-test

Since Nov 09 18:30 each test invocation launches two tests with one test getting aborted after less than a minute.

**Comment by vicaire** [comment] 2019-03-26 21:52
duplicate of https://github.com/kubeflow/pipelines/issues/192

**Closed by vicaire** 2019-03-26 21:52 UTC
