### ISSUE TITLE
Exit handler task does not have proper name in the UX

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1051] opened 2019-03-27 00:39 UTC
![image](https://user-images.githubusercontent.com/1829149/55042291-1387fa00-4fee-11e9-8d94-8da3f5e6f389.png)

The task should be shown as something like: "Exit handler: Delete cluster".

**Comment by vicaire** [comment] 2019-03-27 01:49
Looks like a duplicate of https://github.com/kubeflow/pipelines/issues/78

**Comment by rileyjbauer** [comment] 2019-03-27 05:25
I think this is different. #78 is more about the output of the DSL and the interface between that output and the frontend. This is more just a question of if we can come up with a friendlier name for these nodes, which I believe we can, something like `onExit - TEMPLATE_NAME`

@ajayalfred we style exit handler nodes in the static graph like this:
![image](https://user-images.githubusercontent.com/34456002/55052323-b99b2a80-5015-11e9-873a-11b30a3e4b92.png)


Should we similarly color that node in the runtime graph like so? (note that hovering over the node will display the untruncated name as a tooltip)
![image](https://user-images.githubusercontent.com/34456002/55052365-ec452300-5015-11e9-8677-b67c3b21ca03.png)

Alternatively, we can leave it white:
![image](https://user-images.githubusercontent.com/34456002/55052416-14cd1d00-5016-11e9-93ac-01b0a70084ce.png)

**Comment by vicaire** [comment] 2019-03-27 16:22
Thanks for the clarification @rileyjbauer.

**Comment by ajayalfred** [comment] 2019-03-27 18:29
I think the standard node treatment (white container) for the exit handlers is fine. Grey on grey doesn't provide enough contrast.

**Comment by Ark-kun** [comment] 2019-03-27 19:48
On one hand, I like the  the standard treatment (the last image).
On another hand, I'm worrying about drawing connections with every other node is going to overcomplicate the graph if the graph has many nodes.

**Closed** 2019-03-29 04:24 UTC
Labels: area/front-end, kind/bug, priority/p2
