### ISSUE TITLE
Kubeflow pipeline cannot get graph and state of a run

### ISSUE THREAD

**Issue by Windrill** [kubeflow/pipelines#5324] opened 2021-03-18 09:12 UTC
This is a deployment of Kubeflow on Kubernetes. Previously, Kubeflow was running fine. From one day, all newly created runs cannot get any other status than 'Unknown'. Inside the run, the 'Graph' tab is stuck at loading forever. Run outputs stay at none, and the 'Config' tab shows everything as expected.

From the Argo UI, every run is still functioning correctly, and the logs and artifacts are accessible as normal.
![image](https://user-images.githubusercontent.com/13634511/111600541-7b076780-880c-11eb-85bb-cae3a94a8b2f.png)
![image](https://user-images.githubusercontent.com/13634511/111600605-8b1f4700-880c-11eb-9b55-6a5bb4311c3e.png)

Kubeflow version (the version of kubeflow source code specified in the manifest file used to deploy kubeflow) is around 1.1

If the graph is left to load, from the console, there are a few error requests, if it is relevant:
GET http://[ip]:31380/pipeline/apis/v1beta1/runs/01d0ca69-931d-42c2-afa7-4bf0f72f08cf 500

Utils.tsx:32 Response for path: system/project-id was not 'ok'
Response was: upstream request timeout

What communication could have gone wrong?

**Comment by Bobgy** [comment] 2021-03-19 01:14
Duplicate of https://github.com/kubeflow/pipelines/issues/3763

**Comment by Bobgy** [comment] 2021-03-19 01:14
Can you confirm?

**Comment by Windrill** [comment] 2021-03-19 01:57
Confirmed this fixes the issue
`kubectl delete pod ml-pipeline-persistenceagent-xxxxxxx-xxxx -n kubeflow`

Also observed that the persistence-agent was looping over an old copy of pipelines possibly from a previous deployment of Kubeflow on Kubernetes that has already been reset by kubeadm on the same machine.

After the restart, the correct pipelines are being read correctly and the status of new runs can be displayed.

**Comment by Bobgy** [comment] 2021-03-19 02:58
Thanks for the confirmation, if you have additional information how this situation could happen, please comment on #3763, that will be very helpful. I could not reproduce it any more.

I am closing this issue to allow all discussion happen in the same thread

**Closed by Bobgy** 2021-03-19 02:58 UTC
Labels: kind/bug, needs more info
