### ISSUE TITLE
kfp-kubernetes - module 'kfp.kubernetes' has no attribute 'use_config_map_as_volume'

### ISSUE THREAD

**Issue by sureshmol** [kubeflow/pipelines#10673] opened 2024-04-05 14:43 UTC
### Environment
Kubeflow is installed on a Standalone Kubernetes cluster

*  KFP version:
Version of Kubeflow : v1.8.0

*  All dependencies version:

```
kfp                          2.7.0
kfp-kubernetes               1.1.0
kfp-pipeline-spec            0.3.0
kfp-server-api               2.0.5
```

### Steps to reproduce

I want to attach configmap to my pipeline components

```
from kfp import dsl
from kfp import kubernetes

@dsl.component
def print_config_map():
    with open('/mnt/my_vol') as f:
        print(f.read())

@dsl.pipeline
def pipeline():
    task = print_config_map()
    kubernetes.use_config_map_as_volume(task,
                                       config_map_name='my-cm',
                                       mount_path='/mnt/my_vol',
                                        optional=True)
```

Running this code is resulting in this error:

> AttributeError: module 'kfp.kubernetes' has no attribute 'use_config_map_as_volume'

### Expected result

configMap should be accessible by kubeflow pipeline components

### Materials and Reference

I have used the code snippets from this doc: https://github.com/kubeflow/pipelines/blob/master/kubernetes_platform/python/README.md

---

Impacted by this bug? Give it a 👍.

**Comment by rimolive** [comment] 2024-04-05 15:24
Not a bug. This feature was merged after KFP SDK 2.7.0 was released.

cc @connor-mccarthy Do you have an ETA on the next SDK release date?

**Comment by sureshmol** [comment] 2024-04-08 11:20
Hello @rimolive ,

Is there any way where we can use config maps of my cluster inside kubeflow pipeline components?

**Comment by connor-mccarthy** [comment] 2024-04-08 20:00
cc @Tomcli regarding next release

**Comment by Tomcli** [comment] 2024-04-08 21:00
This feature is from `kfp-kubernetes` sdk, so you can install from source:
```
pip install git+https://github.com/kubeflow/pipelines.git@master#subdirectory=kubernetes_platform/python
```

**Comment by harshad16** [comment] 2024-04-09 18:46
@rimolive  can you please take a look at this one as well: https://github.com/kubeflow/pipelines/issues/10653

**Comment by Tomcli** [comment] 2024-04-09 19:28
@connor-mccarthy Could you cut a 1.2.0 release for the `kfp-kubernetes` SDK? We have added many new features since then and I believe now is a good time to cut the SDK release to unblock our users.

**Comment by harshad16** [comment] 2024-04-11 03:18
@rimolive @Tomcli  seems like this is also https://github.com/kubeflow/pipelines/issues/10687
related to the 1.2.0 release of the kfp-kubernetes.

**Comment by rimolive** [comment] 2024-04-15 22:21
/close

As announced in #10685 kfp-kubernetes 1.2.0 has just released.

**Closed by rimolive** 2024-04-15 22:21 UTC
Labels: kind/bug, area/sdk
