### ISSUE TITLE
[bug] Set a gpu limit on a ContainerOp using a pipeline parameter input

### ISSUE THREAD

**Issue by jdalbosc-cisco** [kubeflow/pipelines#6858] opened 2021-11-03 16:55 UTC
### What steps did you take

I’m using Kfp 1.6.4 to define a pipeline. I would like to set a gpu limit on a ContainerOp using a pipeline parameter input. I have the following pipeline definition:
```
@dsl.pipeline(name="darknet-train-pipeline", description="Trains a darknet network")
def darknet_train_pipeline(...
                           num_gpus: int, ...) -> None:
    ...
    training_op = kfp.components.load_component_from_file(
        os.path.join(os.path.dirname(__file__), 'components/darknet_framework/training/component.yaml'))
    training_task = training_op(another_task.output)
    training_task.set_gpu_limit(num_gpus) # here a TypeError exception is raised
```

### What happened:
When I try to call set_gpu_limit on my ContainerOp I have the following TypeError exception:
```
File "/Users/jean-francois.dalbos/work/git/darknet_models/venv/lib/python3.9/site-packages/kfp/dsl/_container_op.py", line 380, in set_gpu_limit
    self._container_spec.resources.accelerator.count = int(gpu)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'PipelineParam'
```
### What did you expect to happen:
I want Kfp to create a pipeline definition where the gpu limit depends on the pipeline input parameter named num_gpus. In the argo workflow, I would expect something like (not quite sure of the syntax though):

limits: {memory: 4G, nvidia.com/gpu: {{inputs.parameters.num_gpus}} }

### Environment:

*  How do you deploy Kubeflow Pipelines (KFP)? 
In Kubeflow 1.3 UI, uploading the pipeline as an argo workflow yaml file.
 
*  KFP version: 
1.3
*  KFP SDK version: 
1.6.4

### Labels

/area sdk

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by andreyvelich** [comment] 2021-11-03 18:13
@Bobgy @zijianjoy Please can you take a look at this issue.

**Comment by chensun** [comment] 2021-11-04 07:17
I think this is resolved in.the later version of the SDK.
@jdalbosc-cisco Can you please upgrade your sdk and try again?

**Comment by jdalbosc-cisco** [comment] 2021-11-04 08:25
@chensun Thank you for your reply.

I've upgraded kfp to 1.8.9 and indeed the problem is solved. The content of the yaml argo workflow is now:
```
      resources:
        limits: {nvidia: '{{inputs.parameters.num_gpus}}', memory: 4G}
```
Which is what I wan't I guess (not sure about nvidia not being nvidia/gpu but apart from that it's ok).

Now the problem is that when I try to load this yaml in Kubeflow 1.3 UI I have an error message complaining about the format of the quantity not being valid:
**Pipeline version creation failed**
_{"error_message":"Error creating pipeline version: Create pipeline version failed: Failed to get parameters from the workflow: InvalidInputError: Failed to parse the parameter.: error unmarshaling JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'","error_details":"Error creating pipeline version: Create pipeline version failed: Failed to get parameters from the workflow: InvalidInputError: Failed to parse the parameter.: error unmarshaling JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"}_

I guess I might have to update to a newer version of Kubeflow like 1.4 (which I am not in control of)?

**Comment by zijianjoy** [comment] 2021-11-05 01:10
Hello @jdalbosc-cisco , can you upload a simplified version of your pipeline version file? So we can try it out on the latest version of KFP backend v1.7.1 to see whether this issue is fixed.

**Comment by jdalbosc-cisco** [comment] 2021-11-05 08:33
Hello @zijianjoy,

Thank you for your reply.

Here are two file that enable to reproduce the problem (rename to .txt to workaround Github extension filtering). The first one is the code that compiles the pipeline, and the second one is the pipeline yaml file created with the latest version of Kfp 1.8.9.

When I try to upload the gpu_sum.yaml file in the _Upload Pipeline or Pipeline version_ of the Kubeflow 1.3 UI and click on _Create_ to create the pipeline, I have the following error message that shows up in the UI that prevents me from uploading the pipeline:

**Pipeline version creation failed**

_{"error_message":"Error creating pipeline: Create pipeline failed: Failed to get parameters from the workflow: InvalidInputError: Failed to parse the parameter.: error unmarshaling JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'","error_details":"Error creating pipeline: Create pipeline failed: Failed to get parameters from the workflow: InvalidInputError: Failed to parse the parameter.: error unmarshaling JSON: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"}_

Hope this helps.
Regards,

[compile.py.txt](https://github.com/kubeflow/pipelines/files/7481670/compile.py.txt)
[gpu_sum.yaml.txt](https://github.com/kubeflow/pipelines/files/7481671/gpu_sum.yaml.txt)

**Comment by zijianjoy** [comment] 2021-11-10 01:50
This seems like an argo issue, backend doesn't accept this format because of this line in gpu_sum.yaml:
```
limits: {memory: 100M, nvidia: '{{inputs.parameters.num_gpus}}'} 
```

It doesn't fit in the format validation:

```
'^([+-]?[0-9.]+)([eEinumkKMGTP][-+]?[0-9])$'"
```

I think either KFP backend or Argo failed to recognize this as parameter, cc @Bobgy to confirm.

**Comment by veiii** [comment] 2021-11-24 08:15
> This seems like an argo issue, backend doesn't accept this format because of this line in gpu_sum.yaml:
> 
> ```
> limits: {memory: 100M, nvidia: '{{inputs.parameters.num_gpus}}'} 
> ```
> 
> It doesn't fit in the format validation:
> 
> ```
> '^([+-]?[0-9.]+)([eEinumkKMGTP][-+]?[0-9])$'"
> ```
> 
> I think either KFP backend or Argo failed to recognize this as parameter, cc @Bobgy to confirm.

I have the same issue on Kubeflow 1.4 (deployed by manifest), KFP backend v1.7.0.  KFP SDK 1.8.9

**Comment by ashrafgt** [comment] 2021-12-23 20:26
@zijianjoy 

> This seems like an argo issue, backend doesn't accept this format ...

Please try submitting this argo workflow which has pretty much the same GPU limit syntax and worked fine for me (argo version that comes with KFP 1.4):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: cuda-vector-add
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: gpus
      value: 0
  templates:
  - name: main
    container:
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits: {memory: 100M, nvidia: '{{workflow.parameters.gpus}}'} 
```


If it's any help, please consider using this very simple pipeline as a minimum reproducible example:
```python
import kfp
from kfp import dsl

@kfp.components.func_to_container_op
def test():
    print("test")

@dsl.pipeline(name="Test")
def test_pipeline(gpus: int = 0):
    test_task = test()
    test_task.set_cpu_request("4").set_memory_request("4Gi").set_gpu_limit(gpus)
    test_task.container.image = "k8s.gcr.io/cuda-vector-add:v0.1"

if __name__ == "__main__":
    kfp.compiler.Compiler().compile(
        pipeline_func=test_pipeline,
        package_path=__file__.replace(".py", ".yaml"),
    )
```

This bug is a major issue for our team, given that we upload pipelines in a GitOps sort of way. I hope you could look into it soon.

**Comment by zijianjoy** [comment] 2022-01-04 18:48
Hello @ashrafgt , after some investigation, we now think that we should create PodSpecPatch for GPU resources. Refer to issues:

https://github.com/kubeflow/pipelines/issues/1956
https://github.com/kubeflow/pipelines/issues/4877

PodSpecPatch example is in https://github.com/argoproj/argo-workflows/blob/master/examples/pod-spec-patch.yaml. Please note that both examples you provided (argo workflow yaml and KFP pipeline in python) have failed for the same error message on my side. This is why I think we should change to use podSpecPatch.

**Comment by ashrafgt** [comment] 2022-01-04 19:42
@zijianjoy Thank you for checking this! I think the argo example probably didn't work because you're using an older version. I remember that I had tl use pod spec patches before, but not anymore. Regardless of how it's implemented, it'll be great to be able to dynamically control GPU resources :)

**Comment by jdalbosc-cisco** [comment] 2022-01-07 15:46
Thanks @zijianjoy, using kfp 1.8.9, **add_resource_request** and **add_resource_limit** methods instead of set_gpu_limit, I was able to specify a gpu limit using a pipeline input parameter. The updated code below that worked for me.
Thanks again! :slightly_smiling_face:

```
import functools
import kfp
import kfp.components


def set_resources(cpu: str = '200m', memory: str = '100M', gpu: int = None):
    """
    This is a decorator that applies CPU and memory settings to the specified component (pod).

    For security reasons, the following rules must be adhered to pass pod validations on the cluster:
      - CPU limits must not be set
      - CPU request must be set
      - Memory limits and requests must be set and equal
    """
    def decorator(component_op):
        @functools.wraps(component_op)
        def wrapper(*args, **kwargs):
            component = component_op(*args, **kwargs)
            component.set_cpu_request(cpu)
            component.set_memory_request(memory)
            component.set_memory_limit(memory)
            if gpu is not None:
                component.set_gpu_limit(gpu)
            return component
        return wrapper
    return decorator

def gpu_sum_pipeline(num_gpus: int, a: float = 1., b: float = 2.):
    @set_resources(gpu=None)
    def gpu_sum_op(a: float, b: float) -> None:
        def gpu_sum(a: float, b: float) -> None:
            print(a+b)
        gpu_sum_task_factory=kfp.components.create_component_from_func(gpu_sum,
            base_image='python:3.9')
        return gpu_sum_task_factory(a, b)

    gpu_sum_task = gpu_sum_op(a, b)
    gpu_sum_task.add_resource_request('nvidia.com/gpu', num_gpus)
    gpu_sum_task.add_resource_limit('nvidia.com/gpu', num_gpus)

kfp.compiler.Compiler().compile(
    pipeline_func=gpu_sum_pipeline,
    package_path='gpu_sum.yaml')
```

**Comment by zijianjoy** [comment] 2022-02-04 20:48
It is awesome to see your problem resolved!

**Closed by zijianjoy** 2022-02-04 20:48 UTC
Labels: kind/bug, area/sdk, needs more info

**Comment by Bear1110** [comment] 2022-04-27 15:49
Can I use like this example?
```
@dsl.pipeline()
def pipeline(
    timestamp: str, tag: str, language: str,
):

op = dsl.ContainerOp(
        name=f'en-clustering-{timestamp}',
        image=f'{REGISTRY_IMAGE}/clustering_stage:{tag}',
        command=['python3'],
        arguments=[
            'main.py', timestamp, 1, language,
            params_str,
            output_path
        ],
    )

with dsl.Condition(tag == 'prod'):
        if gpu:
            op.set_cpu_limit("2500m")
            op.set_memory_limit("8000Mi")
        else:
            op.set_cpu_limit("800m")
            op.set_memory_limit("4000Mi")

    if gpu:
        op.add_resource_limit('gpu.ailabs.tw/geforce-rtx-2080-ti', '1')
    op.set_cpu_request("20m")
    op.set_memory_request("50Mi")

```
I want to set resource limit when tag value is "prod".
I already do like above code.
However, it does not work.
Can anyone give me help? Thanks

**Comment by gudgud96** [comment] 2025-01-20 07:32
How does this work now with KFP V2? Because seems like the IR YAML is always static and cannot take in pipeline arguments to instantiate cluster resources, such as `{{inputs.parameters.num_gpus}}`.

The following minimal script also failed:
```python
import kfp
from kfp import dsl
from kfp import components


@dsl.component(base_image="python:3.9")
def train_op():
    return dsl.ContainerOp(
        name="Train",
        image="python:3.9",
        command=["python"],
        arguments=["-c", "print('Hello, world!')"],
    )

@dsl.pipeline(name="Test")
def test_pipeline(gpus: int = 0):
    test_task = train_op()
    test_task.set_cpu_request("4").set_memory_request("4Gi").set_gpu_limit(gpus)


if __name__ == "__main__":
    kfp.compiler.Compiler().compile(
        pipeline_func=test_pipeline,
        package_path=__file__.replace(".py", ".yaml"),
    )
```

with the following error:
```
ValueError: invalid literal for int() with base 10: '{{channel:task=;name=gpus;type=Integer;}}'
```

`kfp==2.11.0`
