### ISSUE TITLE
[sdk] packages_to_install not working correctly after upgrading to V2

### ISSUE THREAD

**Issue by Pringled** [kubeflow/pipelines#9974] opened 2023-09-12 08:07 UTC
#### Relevant package versions
kfp==2.1.3
google-cloud-pipeline-components==2.3.1
google-cloud-aiplatform==1.32.0
kfp-pipeline-spec== 0.2.2
kfp-server-api == 2.0.1

### Steps to reproduce
After upgrading to KFP V2, Initializing a component as follows doesn't work:

```python
from kfp.dsl import component

@component(
    base_image="python:3.10",
    packages_to_install=["google-cloud-aiplatform"],
)
def my_function():
    from google.cloud import aiplatform
```
This gives the error `ModuleNotFoundError: No module named 'google.api_core'`, while in KFP V1 (< 2.0), this worked without any issues. It seems to be an issue with 'packages_to_install'. Adding 'google_api_core' to the 'packages_to_install' then throws the error `ModuleNotFoundError: No module named 'grpc'`, adding that gives `RuntimeError: Please install the official package with: pip install grpcio`, adding that gives `ModuleNotFoundError: No module named 'google.rpc'`, and finally, adding that gives `ERROR: No matching distribution found for google.rpc`. It seems that the 'packages_to_install' do not install their dependencies correctly, or there is an issue with 'google-cloud-aiplatform- and KFP V2.

### Expected result

The 'packages_to_install' are installed correctly and can be imported within the component. With the following versions, and the exact same code, this behavior does work:
kfp==1.8.14
google-cloud-pipeline-components==1.0.26
google-cloud-aiplatform==1.18.3

**Comment by Lothiraldan** [comment] 2023-09-12 12:41
I've been impacted by this change as well and I think it's a behavior change in the latest version of KFP 2.1.3 only. I was able to get my pipeline running by using KFP 2.0.1.

I think the "issue" might be coming from the following commit https://github.com/kubeflow/pipelines/pull/9886/commits/80881c12ee2a23688cd7bd5e6eeb330228949cf8 that added `--no-deps` to the pip install command.

**Comment by Pringled** [comment] 2023-09-12 16:06
@Lothiraldan Thank you, that was indeed the problem! Everything works as expected when I downgrade to KFP 2.0.1. I  do wonder why this change was implemented since it makes it seemingly impossible to properly instill packages via 'packages_to_install'. I'll keep this open for now since I'm curious if it's intended behavior or a bug.

**Comment by GfxKai** [comment] 2023-09-13 11:09
Having the same issue, feels like a crazy "feature" to require manually listing every single transitive dependency before your component can run 😅

I think the intention behind the PR was to remove the compile time dependencies of `kfp` for the runtime environment, which makes sense. However, because `kfp=={version} --no-deps` is appended to the `packages_to_install` list, all user-specified dependencies get the same `--no-deps` treatment... definitely feels like a regression!

**Comment by chensun** [comment] 2023-09-13 20:04
@GfxKai is right on point. This is not the intended behavior but a bug. 

/assign @connor-mccarthy

**Comment by chensun** [comment] 2023-09-14 22:45
This was fixed by the latest SDK 2.2.0 release.

**Closed by chensun** 2023-09-14 22:45 UTC
Labels: kind/bug, area/sdk
