### ISSUE TITLE
[backend] API updates for v2.1.0 release causing CI/Unit Test failures

### ISSUE THREAD

**Issue by gmfrasca** [kubeflow/pipelines#10630] opened 2024-03-27 22:30 UTC
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? N/A
*  KFP version: 2.1.0
*  KFP SDK version: 2.7.0

### Steps to reproduce
For one, `go test -v ./backend/...` produces many compile errors

### Expected result
Unit tests should not fail due to compilation errors

Impacted by this bug? Give it a 👍.

**Comment by Tomcli** [comment] 2024-03-27 22:45
Duplicate of #10629, but I guess we created at the same time.

**Comment by chensun** [comment] 2024-03-28 03:34
Let's dedupe to the oldest bug.

**Closed by chensun** 2024-03-28 03:34 UTC
Labels: kind/bug, area/backend
