### ISSUE TITLE
Unable to run Kubeflow fairing from Kubeflow pipeline

### ISSUE THREAD

**Issue by raviranjan0309** [kubeflow/pipelines#3742] opened 2020-05-12 07:01 UTC
Hi,

I was trying to run Kubeflow fairing lightGBM example for distributed parallel training from Kubeflow pipeline. I was successfully able to run the code from local machine by establishing a connection with Kubeflow cluster in GKE.

Then, I tried to run Kubeflow fairing example from Kubelow pipeline. I was able to pull docker image from GCR, spin four machines (1 chief and 3 worker nodes) for distributed parallel training.

I am getting credentials/secrets error while running from Kubeflow pipeline. Detailed error:

**[W 200509 16:17:47 gcp:71] could not check for secret: (403)
95 Reason: Forbidden
96 HTTP response headers: HTTPHeaderDict({‘Audit-Id’: ‘0a89dcc5-f4dc-4c5b-a5b2-63976db59c73’, ‘Content-Type’: ‘application/json’, ‘X-Content-Type-Options’: ‘nosniff’, ‘Date’: ‘Sat, 09 May 2020 16:17:47 GMT’, ‘Content-Length’: ‘301’})
97 HTTP response body: {“kind”:“Status”,“apiVersion”:“v1",“metadata”:{},“status”:“Failure”,“message”:“secrets is forbidden: User \“system:serviceaccount:kubeflow:pipeline-runner\” cannot list resource \“secrets\” in API group \“\” in the namespace \“kubeflow\“”,“reason”:“Forbidden”,“details”:{“kind”:“secrets”},“code”:403}
IOError: [Errno 2] No such file or directory: ‘/etc/secrets/user-gcp-sa.json’**

Version details:
Python - v3.7.3
Kubeflow version (kfctl) - v1.0.2
kfp version - v0.1.37
Kubeflow fairing version - v0.7.2

Could the team please help me to solve this issue? Let me know if more detail needed.

**Comment by Ark-kun** [comment] 2020-05-12 07:49
`User \“system:serviceaccount:kubeflow:pipeline-runner\” cannot list resource \“secrets\” in API group \“\” in the namespace \“kubeflow\“`

Most likely, the `pipeline-runner` user does not have permission to `list` `secrets`. You'll need to expand the role of that user if you want to allow that.

**Comment by raviranjan0309** [comment] 2020-05-12 09:28
The main issue is "IOError: [Errno 2] No such file or directory: ‘/etc/secrets/user-gcp-sa.json’"

It is not able to find the secrets to perform operations.

**Comment by Ark-kun** [comment] 2020-05-13 02:13
I'm not sure why fairing wants to list the secrets. By default `pipeline-runner` SA does not have this:
https://github.com/kubeflow/manifests/blob/9e6ef8681003c195560fb7b3b75211830c19b7a0/pipeline/pipelines-runner/base/cluster-role.yaml#L9

You can modify the `pipeline-runner` *ClusterRole* to allow the `pipeline-runner` SA to list the secrets.

...

Can you please provide a repro and more information for debugging?

Does you cluster have the `user-gcp-sa` secret? Can you use that secret in pipelines?

>kfp version - v0.1.37

This looks pretty old...

**Comment by raviranjan0309** [comment] 2020-05-13 04:39
I have shared the code and detailed error at below URL for debugging:

[https://github.com/raviranjan0309/kubeflow-fairing-pipeline](https://github.com/raviranjan0309/kubeflow-fairing-pipeline)

I have masked GCP project id in the code, please update that to run at your side.

Yes, I have verified, my Kubeflow cluster has user-gcp-sa secret under kubeflow and kubeflow-ext namespace. I am able to use the secrets in Kubeflow pipelines.

I have updated kfp to below latest versions:
kfp==0.5.1
kfp-server-api==0.5.0

But, I am still getting the same error.

**Comment by Bobgy** [comment] 2020-05-15 06:27
I don't quite understand the error message, one thing strange is that, it is finding secret at `/etc/secrets/user-gcp-sa.json`. But for KFP, the secret should by default be mounted at `/secret/gcp-credentials/` https://github.com/kubeflow/pipelines/blob/e2e30a379cd20dfe3a25131fcaaed203e70a6da1/sdk/python/kfp/gcp.py#L18.

Looking at your example pipeline code, you were not overriding that parameter. Sounds another library is trying to get user-gcp-sa.json, but it looked at a wrong location? Can you try trouble shooting that, I'm not sure that's a problem of KFP.

**Comment by raviranjan0309** [comment] 2020-05-15 09:35
I tried to troubleshoot that but every time it's trying to find secrets at `/etc/secrets/user-gcp-sa.json ` whereas the default value is `/secret/gcp-credentials/`. I tried to override the parameter but no success yet.

Need experts help to resolve this. Happy to provide any more info.

**Comment by Ark-kun** [comment] 2020-05-16 05:51
I've looked at the logs and the fairing code.

I think my solution still stands:

>I'm not sure why fairing wants to list the secrets. By default pipeline-runner SA does not have this:
https://github.com/kubeflow/manifests/blob/9e6ef8681003c195560fb7b3b75211830c19b7a0/pipeline/pipelines-runner/base/cluster-role.yaml#L9

>You can modify the pipeline-runner ClusterRole to allow the pipeline-runner SA to list the secrets.

The root cause is as I expected: The issue occurs with the pods launched by fairing, not the pods launched by KFP/Argo. This explains why the secret path is different. The reason why does  not mount the secret to the pods it launches is because it fails to detect the presence of the GCP secret. Why? As stated in the initial logs: "User \“system:serviceaccount:kubeflow:pipeline-runner\” cannot list resource \“secrets\” in API group \“\” in the namespace \“kubeflow\“". Fairing checks the presence of the secret by using `list` instead of `get` and when `list` fails sue to lack of permission, it just does not attach any secrets to the pod.

So, my first comment https://github.com/kubeflow/pipelines/issues/3742#issuecomment-627175063 still stands. As well as the second https://github.com/kubeflow/pipelines/issues/3742#issuecomment-627702617 . You need to give `pipeline-runner` permission to list secrets.

https://github.com/kubeflow/fairing/blob/3fb8dbc5970008a60eb4832550053aa1f2f215dd/kubeflow/fairing/cloud/gcp.py#L60

https://github.com/kubeflow/fairing/blob/e0d44e870b467bbd773f836a8b1b648b79019dd1/kubeflow/fairing/kubernetes/manager.py#L220

**Comment by raviranjan0309** [comment] 2020-05-19 02:23
It worked for me. I am able to run Kubeflow fairing from Kubeflow pipeline successfully.

Thank you so much for your support and guidance.

**Comment by Bobgy** [comment] 2020-05-19 02:30
@Ark-kun do you think if we need to add documentation somewhere? or we can just close this?

**Comment by raviranjan0309** [comment] 2020-05-19 03:59
I would suggest to document it somewhere so that anyone wants to run Kubeflow fairing from Kubeflow pipeline in the future will refer for troubleshooting. Please let me know where to document it.

I would also suggest adding ```list``` in ClusterRole for pipeline-runner that will solve this for everyone. I have raised a PR for this. Please share your inputs.

**Comment by Ark-kun** [comment] 2020-05-19 04:46
I've opened the issue in Fairing repo https://github.com/kubeflow/fairing/issues/494
Closing this one.

**Closed by Ark-kun** 2020-05-19 04:46 UTC
Labels: area/troubleshoot, needs investigation, status/triaged

**Comment by namlh16** [comment] 2022-03-10 10:50
> It worked for me. I am able to run Kubeflow fairing from Kubeflow pipeline successfully.
> 
> Thank you so much for your support and guidance.

please how you grant permission for pipeline-runner ? @raviranjan0309
