### ISSUE TITLE
kubeflow v0.5.1 ml-pipeline-persistenceagent-55b6f879fc-wf2s8 

### ISSUE THREAD

**Issue by UrmsOne** [kubeflow/pipelines#1609] opened 2019-07-11 11:58 UTC
restarts forever and the logs detail 

time="2019-07-11T11:49:06Z" level=fatal msg="Error creating ML pipeline API Server client: Failed to initialize pipeline client. Error: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline.kubeflow-dev.svc.cluster.local:8888/apis/v1beta1/healthz: dial tcp: lookup ml-pipeline.kubeflow-dev.svc.cluster.local: no such host: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline.kubeflow-dev.svc.cluster.local:8888/apis/v1beta1/healthz: dial tcp: lookup ml-pipeline.kubeflow-dev.svc.cluster.local: no such host"

**Comment by IronPan** [comment] 2019-07-11 18:39
Is API server running well in the kubeflow-dev namespace?

**Comment by chwonghk01** [comment] 2019-07-12 03:58
Same here, got the exact issue after running `kubectl delete po --all` (trying to restart kubeflow)
```
$ kubectl logs ml-pipeline-persistenceagent-57f46f4b88-wpxbx
W0712 03:53:13.555466       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2019-07-12T03:55:26Z" level=fatal msg="Error creating ML pipeline API Server client: Failed to initialize pipeline client. Error: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline.kubeflow.svc.cluster.local:8888/apis/v1beta1/healthz: dial tcp: lookup ml-pipeline.kubeflow.svc.cluster.local: no such host: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline.kubeflow.svc.cluster.local:8888/apis/v1beta1/healthz: dial tcp: lookup ml-pipeline.kubeflow.svc.cluster.local: no such host"
```

**Comment by UrmsOne** [comment] 2019-07-12 04:31
@IronPan   @chwonghk01 
Thanks，I finally found out that my reason was the k8s dns doesn't match.
ml-pipeline.kubeflow.svc.cluster.local -> kube-dns.kube-system.svc.k8s.xxx.xxx.local
So,I try to modify the confirguration to overwrite it.

**Comment by chwonghk01** [comment] 2019-07-12 04:33
Good job @UrmsOne !
Do you have the detail steps to check the setting and fix the issue? I am relatively new to kubeflow.

**Comment by jessiezcc** [comment] 2019-07-16 21:02
closing issue since the issue is resolved, feel free to follow up offline.

**Closed** 2019-07-16 21:01 UTC

**Comment by Excelight** [comment] 2019-07-19 18:10
I have the same problem. @chwonghk01 Do you have resolved it?
@UrmsOne Could you share some details about fixing this?

**Comment by wdhorton** [comment] 2019-10-07 21:54
Seeing this issue too, would appreciate any details about a fix

**Comment by UrmsOne** [comment] 2019-10-08 07:47
@Excelight  @wdhorton 

Firstly, you need to identify the cause of the problem.

You should confirm that the DNS of k8s cluster is working. 

If you change the k8s cluster default clusterDomain(defualt: "cluster.local"), you should try to modify the confirguration to overwrite it. My cluster environment changed the default clusterDoamin,so I met this issue.

Depending on how the project is implemented, there are three options:

1) By modifying the environment variables of the docker container.

![image](https://user-images.githubusercontent.com/31981402/66376213-b11ea600-e9e1-11e9-9716-bcdeece9fa07.png)

2) By modifying the docker container‘s configuration file(k8s volumn or configMap)


3) By modifying the string in the source code

![image](https://user-images.githubusercontent.com/31981402/66376019-4c634b80-e9e1-11e9-8de1-ae5744455b37.png)

What's the output when you kubectl get -n kubeflow po <your-ml-pipeline-persistenceagent> -o yaml?

Could you also provide the logs from its Pod?
