### ISSUE TITLE
HTTP response body: RBAC: access denied from kfp_server_api when creating a tfx pipeline

### ISSUE THREAD

**Issue by PatrickGhosn** [kubeflow/pipelines#4976] opened 2021-01-12 17:28 UTC
/kind question

### What steps did you take:
Ran the below code:
![image](https://user-images.githubusercontent.com/33845447/104349736-f77b8280-550b-11eb-9e2c-907481d7485f.png)

### What happened:
I got the below:
```
HTTP response body: RBAC: access denied
ERROR:root:Failed to get healthz info attempt 4 of 5.
Traceback (most recent call last):
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp/_client.py", line 312, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api/healthz_service_api.py", line 77, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api/healthz_service_api.py", line 162, in get_healthz_with_http_info
    collection_formats=collection_formats)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 383, in call_api
    _preload_content, _request_timeout, _host)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 202, in __call_api
    raise e
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 199, in __call_api
    _request_timeout=_request_timeout)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 407, in request
    headers=headers)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/rest.py", line 248, in GET
    query_params=query_params)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Tue, 12 Jan 2021 17:25:02 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})
HTTP response body: RBAC: access denied
```
### What did you expect to happen:
Being able to create the pipeline

### Environment:
Kubeflow 1.2, Jupyter Notebook

How did you deploy Kubeflow Pipelines (KFP)?

KFP version: 
build version v1beta1

KFP SDK version: 
kfp                            1.3.0
kfp-pipeline-spec              0.1.3.1
kfp-server-api                 1.3.0

### Anything else you would like to add:
I'm using kubeflow in my username's namespace

**Comment by piyongze** [comment] 2021-01-13 06:48
me too.
when run
client = kfp.Client()
print:
ERROR:root:Failed to get healthz info attempt 1 of 5.
Traceback (most recent call last):
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp/_client.py", line 312, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api/healthz_service_api.py", line 77, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api/healthz_service_api.py", line 162, in get_healthz_with_http_info
    collection_formats=collection_formats)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 383, in call_api
    _preload_content, _request_timeout, _host)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 202, in __call_api
    raise e
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 199, in __call_api
    _request_timeout=_request_timeout)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 407, in request
    headers=headers)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/rest.py", line 248, in GET
    query_params=query_params)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Wed, 13 Jan 2021 06:46:40 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})
HTTP response body: RBAC: access denied

**Comment by PatrickGhosn** [comment] 2021-01-13 11:10
> me too.
> when run from notebook server
> client = kfp.Client()
> print:
> ERROR:root:Failed to get healthz info attempt 1 of 5.
> Traceback (most recent call last):
> File "/home/jovyan/.local/lib/python3.6/site-packages/kfp/_client.py", line 312, in get_kfp_healthz
> response = self._healthz_api.get_healthz()
> File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api/healthz_service_api.py", line 77, in get_healthz
> return self.get_healthz_with_http_info(**kwargs) # noqa: E501
> File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api/healthz_service_api.py", line 162, in get_healthz_with_http_info
> collection_formats=collection_formats)
> File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 383, in call_api
> _preload_content, _request_timeout, _host)
> File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 202, in __call_api
> raise e
> File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 199, in __call_api
> _request_timeout=_request_timeout)
> File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 407, in request
> headers=headers)
> File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/rest.py", line 248, in GET
> query_params=query_params)
> File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/rest.py", line 238, in request
> raise ApiException(http_resp=r)
> kfp_server_api.exceptions.ApiException: (403)
> Reason: Forbidden
> HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Wed, 13 Jan 2021 06:46:40 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})
> HTTP response body: RBAC: access denied

For the KFP client you need to call your public endpoint and set the IAP tokens.
```
client = kfp.Client(host='https://test.endpoints.testexample.cloud.goog/pipeline',
    client_id='52352352525-fsd232354252352525.apps.googleusercontent.com',
    other_client_id='52352352525-sdfsdffqwfqwfqwfqwfqf.apps.googleusercontent.com',
    other_client_secret='ggewgerg-wefwg')
```

But I can't find any option to do that with tfx.

**Comment by kmathiou** [comment] 2021-01-13 16:14
Hi,

I am facing the same issue when I try from jupyter. 
Moreover, I cannot even run a pipeline from UI. I get the following error:

> Run creation failed
> {"error":"Failed to authorize the request.: BadRequestError: Experiment is required for CreateRun/CreateJob.: Missing experiment","message":"Failed to authorize the request.: BadRequestError: Experiment is required for CreateRun/CreateJob.: Missing experiment","code":10,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Experiment is required for CreateRun/CreateJob.","error_details":"Failed to authorize the request.: BadRequestError: Experiment is required for CreateRun/CreateJob.: Missing experiment"}]}

Are these issues related?
Is there a fix on this or have we might done anything wrong during installation?

**Comment by PatrickGhosn** [comment] 2021-01-13 16:34
> Hi,
> 
> I am facing the same issue when I try from jupyter.
> Moreover, I cannot even run a pipeline from UI. I get the following error:
> 
> > Run creation failed
> > {"error":"Failed to authorize the request.: BadRequestError: Experiment is required for CreateRun/CreateJob.: Missing experiment","message":"Failed to authorize the request.: BadRequestError: Experiment is required for CreateRun/CreateJob.: Missing experiment","code":10,"details":[{"@type":"type.googleapis.com/api.Error","error_message":"Experiment is required for CreateRun/CreateJob.","error_details":"Failed to authorize the request.: BadRequestError: Experiment is required for CreateRun/CreateJob.: Missing experiment"}]}
> 
> Are these issues related?
> Is there a fix on this or have we might done anything wrong during installation?
No doesn't look related. Try reinstalling, I had a similar issue where experiments and pipelines were not opening from the UI. A reinstall solved it.

**Comment by zyanichaimaa** [comment] 2021-01-15 13:47
Facing the same issue, Any updates on this?

```
ERROR:root:Failed to get healthz info attempt 5 of 5.
Traceback (most recent call last):
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp/_client.py", line 312, in get_kfp_healthz
    response = self._healthz_api.get_healthz()
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api/healthz_service_api.py", line 77, in get_healthz
    return self.get_healthz_with_http_info(**kwargs)  # noqa: E501
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api/healthz_service_api.py", line 162, in get_healthz_with_http_info
    collection_formats=collection_formats)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 383, in call_api
    _preload_content, _request_timeout, _host)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 202, in __call_api
    raise e
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 199, in __call_api
    _request_timeout=_request_timeout)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/api_client.py", line 407, in request
    headers=headers)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/rest.py", line 248, in GET
    query_params=query_params)
  File "/home/jovyan/.local/lib/python3.6/site-packages/kfp_server_api/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kfp_server_api.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'content-length': '19', 'content-type': 'text/plain', 'date': 'Fri, 15 Jan 2021 12:47:15 GMT', 'server': 'envoy', 'x-envoy-upstream-service-time': '0'})
HTTP response body: RBAC: access denied

```

**Comment by rastislavs** [comment] 2021-01-20 15:28
Same issue here. The issue can be work-arounded by disabling RBAC in Istio (`clusterRbacConfig=OFF`). Which of course is not great for mutli-user setups.

**Comment by Windfarer** [comment] 2021-01-22 06:42
Same issue.

**Comment by Mar-ai** [comment] 2021-01-25 10:00
You might find this issue useful: https://github.com/kubeflow/pipelines/issues/4440
Specifically these comments describe how to overcome this by adding a servicerolebinding and envoy filter: https://github.com/kubeflow/pipelines/issues/4440#issuecomment-687553259, https://github.com/kubeflow/pipelines/issues/4440#issuecomment-687689294, https://github.com/kubeflow/pipelines/issues/4440#issuecomment-687703390

**Comment by Bobgy** [comment] 2021-03-05 00:50
Duplicate of #4440

**Closed by Bobgy** 2021-03-05 00:50 UTC
Labels: kind/question

**Comment by alexcpn** [comment] 2021-08-12 13:26
For new clusters please see this comemnt from the issue 4440 

https://github.com/kubeflow/pipelines/issues/4440#issuecomment-871927424

```
cat << EOF | kubectl apply -f -
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: bind-ml-pipeline-nb-kubeflow-user-example-com
 namespace: kubeflow
spec:
 selector:
   matchLabels:
     app: ml-pipeline
 rules:
 - from:
   - source:
       principals: ["cluster.local/ns/kubeflow-user-example-com/sa/default-editor"]
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-header
  namespace: kubeflow-user-example-com
spec:
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: SIDECAR_OUTBOUND
      routeConfiguration:
        vhost:
          name: ml-pipeline.kubeflow.svc.cluster.local:8888
          route:
            name: default
    patch:
      operation: MERGE
      value:
        request_headers_to_add:
        - append: true
          header:
            key: kubeflow-userid
            value: user@example.com
  workloadSelector:
    labels:
      notebook-name: test2
EOF
```
In my notebook 
```

import kfp
client = kfp.Client()
print(client.list_experiments())
```
Output
```
{'experiments': [{'created_at': datetime.datetime(2021, 8, 12, 9, 14, 20, tzinfo=tzlocal()),
                  'description': None,
                  'id': 'b2e552e5-3324-483a-8ec8-b32894f49281',
                  'name': 'test',
                  'resource_references': [{'key': {'id': 'kubeflow-user-example-com',
                                                   'type': 'NAMESPACE'},
                                           'name': None,
                                           'relationship': 'OWNER'}],
                  'storage_state': 'STORAGESTATE_AVAILABLE'}],
 'next_page_token': None,
 'total_size': 1}
```
