### ISSUE TITLE
[question] how to add `tolerations` using sdk `v2`.

### ISSUE THREAD

**Issue by akshatdalton** [kubeflow/pipelines#10252] opened 2023-11-20 13:17 UTC
### Environment

*  KFP version: `2.0.1`

*  KFP SDK version: `2.0.1`

How can I add `tolerations` in kubeflow pipelines/components in kfp `v2`? In `v1`, I can see that there is a method: `add_toleration` but supported in `v1`.

Impacted by this bug? Give it a 👍.

**Comment by zijianjoy** [comment] 2023-12-14 23:45
Duplicate of https://github.com/kubeflow/pipelines/issues/9682

**Comment by rimolive** [comment] 2024-03-07 15:37
Closing this issue as @zijianjoy already marked as duplicated.

/close

**Closed by rimolive** 2024-03-07 15:37 UTC
Labels: kind/bug, area/backend
