### ISSUE TITLE
Plain keras training running via build_image_from_working_dir: OOMKilled

### ISSUE THREAD

**Issue by kierenj** [kubeflow/pipelines#2540] opened 2019-11-04 08:13 UTC
Training a simple Keras model (couple of LSTM layers, 28000x150x27 input), using whatever the default base image is from `kfp.containers.build_image_from_working_dir` following a fresh `pip3 install kfp`, and the container's RAM grows steadily over about 50 minutes until it's `OOMKilled`.

The input data is in CSV format and loaded once initially via `dataset = np.loadtxt(raw_data, delimiter=",")`. The crash happens around the third epoch, i.e. all data has been processed by that point.

The pod YAML does show the correct requests and limits in place. So, something in the environment is not respecting them I think?

```python
image = kfp.containers.build_image_from_working_dir(
    image_name='eu.gcr.io/MY_PROJ/MY_IMAGE',
    file_filter_re=r'.*\.ipynb',
    timeout=3*60*60 # 3 hours
)

my_model_op = kfp.components.func_to_container_op(
    func=bb_make_model,
    base_image=image
)

# ...

make_model = my_model_op(args_here)
cpu_request = cpu_limit = '15'
memory_request = memory_limit = '26Gi'
make_model.container.add_resource_request('cpu', cpu_request)
make_model.container.add_resource_request('memory', memory_request)
make_model.container.add_resource_limit('cpu', cpu_limit)
make_model.container.add_resource_limit('memory', memory_limit)
```

`This step is in Failed state with this message: OOMKilled`

There's some memory allocator output or similar in the logs:

````
First RAM-looking message:
time="2019-11-03T22:17:14Z" level=info msg="Alloc=3248 TotalAlloc=11862 Sys=70846 NumGC=12 Goroutines=11

Final RAM-looking message:
 time="2019-11-03T22:52:14Z" level=info msg="Alloc=3254 TotalAlloc=11952 Sys=70846 NumGC=29 Goroutines=11
````
The 'GC' part looks to point towards Python, and the numbers look like there's nothing going on there. Seems that Tensorflow isn't respecting memory limits? Though I am not an expert here.

The 7 CPU request was to trigger a n1-standard-8 autoprovisioned bool: which it did, which has 30GB, hence my memory limit of 27GB.

I've tried on a much larger machine too - 63 cores, so a n1-standard-64 and 100GB RAM (I thought, 'why not'). It was still terminated for exceeding the limit.

However, I really don't believe the training requires lots of RAM: the same training has previously run on my laptop overnight without issue (which has much less than half the RAM), although that's natively under Windows, as opposed to in whatever environment Kubeflow gives me.

If I jump into the docker image locally with a shell, I can `cat Dockerfile` to see what Kubeflow has prepared for me:
````
FROM gcr.io/deeplearning-platform-release/tf-cpu.1-14
WORKDIR /python_env
COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt
COPY . .
````

I'm still on my quest to get a pipeline up and running on Kubeflow. I'm a few weeks in and tantalisingly close. I have a pipeline defined and uploaded from a Notebook, lots of preprocessing steps from other docker images (running .NET Core code), passing data between components. The final step is the struggle: I tried fairing, but simply could not get any combination to work. Now I'm here. The model is super simple, 7 lines of Keras. I'd appreciate any pointers at all.

I also realise that there's a house of cards of components, and Kubeflow may not be the way to solve it. If it's a dependency of Kubeflow I need to look at, if you could kindly point me in the right direciton please?

**Comment by Ark-kun** [comment] 2019-11-04 08:39
Thank you for your feedback. I'll work with you to make Pipelines work for you. 

I'll add more information later.

1) kfp.containers.build_image_from_working_dir does not do anything magical. You've seen the Dockerfile. It just collects python files, generates Dockerfile and builds image. You may use some other base image that you already know.

2) Tensorflow probably does not respect Kubernetes' limits.

3) Try to use tensorflow base image with the version you've usel locally before.

**Comment by kierenj** [comment] 2019-11-04 21:31
Thanks, previously though I was just running tensorflow locally, not in a container. I'm really stuck at understanding how anyone would have used Tensorflow on Kubernetes ever before if it's not respecting limits. Presumably you/no-one on the Kubeflow project has encountered it? I'm not sure why I would stumble across such an issue for the first time!

I did raise an issue however, here - https://github.com/tensorflow/tensorflow/issues/33960 .

I'm running the code in the same container/image locally now to see what happens.

**Comment by kierenj** [comment] 2019-11-04 21:52
Running the same image locally, the python process termined with a simple "Killed" to stdout. Using dmesg:

````
[ 2045.760028] Out of memory: Kill process 2439 (python3) score 888 or sacrifice child
[ 2045.761277] Killed process 2439 (python3) total-vm:5014356kB, anon-rss:1879228kB, file-rss:0kB, shmem-rss:0kB
[ 2046.137806] oom_reaper: reaped process 2439 (python3), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
````

I'd like to try some other base images.. would anyone have any recommendations? I'm struggling to see why `gcr.io/deeplearning-platform-release/tf-cpu.1-14` wouldn't be ideal for tensorflow on GCP! :)

**Comment by kierenj** [comment] 2019-11-05 18:38
`tensorflow/tensorflow:latest-py3` base image works just fine. This solves it for me, thanks for the tip.

Hoping the issue helps someone in my situation in the future.. shall I close this?

**Comment by Ark-kun** [comment] 2019-11-05 21:22
>tensorflow/tensorflow:latest-py3 base image works just fine.

You should pin the image (use versioned image). Otherwise your pipeline might break in future in TF releases a new incompatible or buggy image.

> I'm really stuck at understanding how anyone would have used Tensorflow on Kubernetes ever before if it's not respecting limits. Presumably you/no-one on the Kubeflow project has encountered it?

I guess people were using smaller models.

Is there any way to tell Tensorflow how much memory it can use? I thought that there si no control over it as the needed memory is determined by the network size.

**Comment by kierenj** [comment] 2019-11-06 08:37
Thanks, I will pin the version.

My model is really very small though. On the correct image the total use is about 3-5GB, whereas with the GCP one (the default for Kubeflow) it didn't stop at 100GB.

**Comment by Ark-kun** [comment] 2019-11-06 21:55
> On the correct image the total use is about 3-5GB, whereas with the GCP one (the default for Kubeflow) it didn't stop at 100GB.

Oh. This sounds like a big issue. Is there any way you can donate a PoC/reproduction, so that I can pass it to the Deep Learning VM team?

**Comment by kierenj** [comment] 2019-11-13 20:17
Sorry, I will do so, hopefully in the next few days

**Comment by Ark-kun** [comment] 2020-04-26 07:16
Closing the bug. The issue is not in KFP.

**Closed by Ark-kun** 2020-04-26 07:16 UTC
Labels: area/sdk, kind/misc
