### ISSUE TITLE
tfx-oss sample test would fail when retry the test

### ISSUE THREAD

**Issue by gaoning777** [kubeflow/pipelines#2354] opened 2019-10-10 06:16 UTC
When I try '/test kubeflow-pipeline-sample-test' for flakiness tests, the parameterized_tfx_oss would always fail due to the fact that they are writing to the same directory.
See: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/2349/kubeflow-pipeline-sample-test/1182166563743076352

**Comment by numerology** [comment] 2019-10-10 15:00
Right... That's similar to the problem of model pushing we observed before. Because the GCS do not update if no new commit is detected, it will fail.

Let me fix it shortly. A quick solution is make the timestamp part of the pipeline root path.

**Comment by Ark-kun** [comment] 2019-10-11 23:36
P.S. From high-level perspective this issue is related to the "intermediate data management" issue.
The error we're getting is when new pipeline tries to overwrite the data stored by another run!
If those data paths were managed by the system, the paths would have always been unique and the data storage would be handled by the system, so the data would never be overwritten.

I've seen this problem quite a few times.
Fortunately, the big data passing support fixes this problem (for cooperating components) at least for the the intermediate data (the problem is impossible to fix exporting data to explicit locations.)

**Comment by numerology** [comment] 2019-10-14 18:45
Fixed by #2360 
For @Ark-kun 's question, that seems to require something similar to data-versioning/spanning. 
Besides big data passing feature, this should also be solved after migrating to unified DSL for TFX distinguishes between different execution by their IDs.

**Closed by numerology** 2019-10-14 18:45 UTC
Labels: area/samples, area/testing
