### ISSUE TITLE
Tensorboard Projector page empty

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#2509] opened 2019-10-29 19:32 UTC
<img width="2407" alt="Screen Shot 2019-10-29 at 7 10 52 PM" src="https://user-images.githubusercontent.com/2348602/67802300-16e1d900-fa48-11e9-949f-fdbc0e6e04e4.png">

This can be reproduced by running the latest prebuilt tfx samples and open the tensorboard in the training step through GCP marketplace.

**Comment by IronPan** [comment] 2019-10-29 19:42
Here is another example that we knew working in previous version of KFP
https://aihub.cloud.google.com/u/0/p/products%2F4a91d2d0-1fb8-4e79-adf7-a35707071195/v/2/downloadpage

**Comment by numerology** [comment] 2019-10-29 20:02
The preload TFX sample does not have projector implemented in its module file. So I guess it should be its intended behavior? However the projector page is blank as well for the AI Hub sample, which is problematic.

**Comment by numerology** [comment] 2019-10-29 20:03
Relevant:
https://github.com/tensorflow/tensorboard/issues/2771

**Comment by jingzhang36** [comment] 2019-10-30 05:13
+1 to @numerology's theory. I downgrade tensorflow to 1.13.2 in my viewer controller and projector works fine

**Comment by IronPan** [comment] 2019-10-30 05:14
What version of tf do we use in viewer controller? do we pull latest?

**Comment by jingzhang36** [comment] 2019-11-05 07:49
Close this issue and track the tb version selector in https://github.com/kubeflow/pipelines/issues/2514

**Closed by jingzhang36** 2019-11-05 07:49 UTC
Labels: kind/bug, priority/p0
