### ISSUE TITLE
No method to upload pipeline version using python sdk

### ISSUE THREAD

**Issue by jonasdebeukelaer** [kubeflow/pipelines#4542] opened 2020-09-24 08:08 UTC
### What steps did you take:
tried to write a python script to upload a new pipeline version.

### What happened:
could not find the `client` method to do so. It seems to have been removed since the below docs were written. https://www.kubeflow.org/docs/pipelines/tutorials/sdk-examples/#example-1-creating-a-pipeline-and-a-pipeline-version-using-the-sdk

### What did you expect to happen:
have an method called `upload_pipeline_version` or similar.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
via KF

KFP version: 1.0.1
KFP SDK version: 1.0.1

### Anything else you would like to add:

/kind bug
/area sdk

**Comment by Ark-kun** [comment] 2020-09-25 07:24
The method exists:
https://github.com/kubeflow/pipelines/blame/master/sdk/python/kfp/_client.py#L846
https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.upload_pipeline_version

I think the problem is that the released version of the SDK uses a really old version. https://github.com/kubeflow/pipelines/issues/4409

**Comment by Bobgy** [comment] 2020-09-29 11:34
That's right, https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.upload_pipeline_version shows master branch, but we released from `release-1.0` branch. The method did get into 1.0 release

**Comment by ConverJens** [comment] 2020-10-22 09:32
@Bobgy Not sure if I have missed something but the upload_pipeline_version you are referring to seems like it didn't go into the kfp 1.0.3 release which is the latest stable one from pypi. From the link you supplied but choosing the release-1.0 instead of latest:
https://kubeflow-pipelines.readthedocs.io/en/release-1.0/source/kfp.server_api.html#kfp-client-pipelines
upload_pipeline_version is not present. It is however present in the kfp-server-api and thus reachable from kfp.Client()._upload_api.upload_pipeline_version but which is an internal api but it works as a workaround.

**Comment by ConverJens** [comment] 2020-10-22 09:45
@Bobgy I think the issue is that if you create a kfp.Client() object, that object has no upload_pipeline_version method. It is only accessible through kfp.Client()._upload_api.upload_pipeline_version which is slightly obscure.

**Comment by Bobgy** [comment] 2020-10-22 10:18
Yes, that's right. The problem should be fixed when we release `1.1.0-alpha.1`.

**Closed by Bobgy** 2020-10-22 10:18 UTC
Labels: area/sdk, kind/bug, priority/p0

**Comment by paveldournov** [comment] 2020-10-26 06:01
> @Bobgy I think the issue is that if you create a kfp.Client() object, that object has no upload_pipeline_version method. It is only accessible through kfp.Client()._upload_api.upload_pipeline_version which is slightly obscure.

Can we add this to the documentation? The [doc ](https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.upload_pipeline_version )doesn't say it is requires the additional indirection.

**Comment by Bobgy** [comment] 2020-10-26 06:13
@paveldournov, @Ark-kun has updated the doc website: https://kubeflow-pipelines.readthedocs.io to show `stable` version by default now (instead of `latest` previously). So it should not show the method to users before its released.

Regarding to using `_upload_api`, I'll need to double check when releasing 1.1.0, if the method is not available through `upload_pipeline_version`, then it's a bug we need to fix. Rather than a documentation issue.
