### ISSUE TITLE
TFJob doesn't forward error logs from the jobs

### ISSUE THREAD

**Issue by sshrdp** [kubeflow/pipelines#407] opened 2018-11-28 22:49 UTC
TF Job doesn't show any information regarding the spawned jobs state and errors in Pipeline UI.

**Comment by yebrahim** [comment] 2018-11-29 22:06
Yes, eventually we would like the UI to surface status of the transitive closure of the run's resources, of which TF Job is an example. This isn't trivial unfortunately, it will require two things:
- Ability to identify such resources, either via run steps transitively adding ownership references, or by using a well-defined API to create further resources.
- Tracking and reporting status for each of those resources in order to surface them in the UI.

**Comment by randxie** [comment] 2019-03-06 21:07
To forward logging from tfjobs to Pipeline UI, it seems to me that we should expand the tf-operator, e.g. adding utility functions to stream logs back to the container where tfjobs runs. IIRC, the current Pipeline UI is able to capture logs from tfjobs container.

**Comment by vicaire** [comment] 2019-03-26 03:40
Closing this issue as a duplicate of #677

**Closed by vicaire** 2019-03-26 03:40 UTC
Labels: area/components, area/front-end
