### ISSUE TITLE
Error running pipeline: cannot create tfjobs.kubeflow.org 403

### ISSUE THREAD

**Issue by lluunn** [kubeflow/pipelines#294] opened 2018-11-15 22:41 UTC
Steps:
1. followed [wiki](https://github.com/kubeflow/pipelines/wiki/Deploy-the-Kubeflow-Pipelines-Service) to deploy pipeline. 
2. I took the [code](https://github.com/amygdala/code-snippets/blob/master/ml/kubeflow-pipelines/samples/kubeflow-tf/workflow1.py#L187) from @amygdala's [blog](https://cloud.google.com/blog/products/ai-machine-learning/getting-started-kubeflow-pipelines), ran it in jupyter notebook to build the tarball
3. Upload the tarball, and graph looks correct:
<img width="997" alt="screen shot 2018-11-15 at 14 39 46" src="https://user-images.githubusercontent.com/32310205/48586267-51f50600-e8e4-11e8-8e4e-923d95308ddc.png">

4. Running the pipeline, got error: 
```
INFO:root:Getting credentials for GKE cluster kfp1.
Fetching cluster endpoint and auth data.
kubeconfig entry generated for kfp1.
INFO:root:Generating training template.
INFO:root:Start training.
ERROR:root:Exception when calling DefaultApi->apis_fqdn_v1_namespaces_namespace_resource_post: tfjobs.kubeflow.org is forbidden: User "system:serviceaccount:kubeflow:pipeline-runner" cannot create tfjobs.kubeflow.org in the namespace "kubeflow"
Traceback (most recent call last):
  File "/ml/train.py", line 230, in <module>
    main()
  File "/ml/train.py", line 188, in main
    create_response = tf_job_client.create_tf_job(api_client, content_yaml, version=kf_version)
  File "/tf-operator/py/tf_job_client.py", line 56, in create_tf_job
    raise e
kubernetes.client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 15 Nov 2018 22:32:05 GMT', 'Audit-Id': '316cc166-62f2-43aa-926e-8014f66f4b2e', 'Content-Length': '318', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"tfjobs.kubeflow.org is forbidden: User \"system:serviceaccount:kubeflow:pipeline-runner\" cannot create tfjobs.kubeflow.org in the namespace \"kubeflow\"","reason":"Forbidden","details":{"group":"kubeflow.org","kind":"tfjobs"},"code":403
``` 

<img width="1008" alt="screen shot 2018-11-15 at 14 40 58" src="https://user-images.githubusercontent.com/32310205/48586329-7bae2d00-e8e4-11e8-9f74-a9489b4f97fa.png">

**Comment by amygdala** [comment] 2018-11-16 01:11
I think the issue is that you need to run this command or similar before running any pipelines:
`kubectl create clusterrolebinding sa-admin --clusterrole=cluster-admin --serviceaccount=kubeflow:pipeline-runner`

**Comment by amygdala** [comment] 2018-11-16 01:13
Here's the related issue: https://github.com/kubeflow/pipelines/issues/220

**Comment by amygdala** [comment] 2018-11-16 17:15
Hmm, I have not seen this (and can't repro).  :(
Do the logs of the tf-job-operator* pod have any clues?

Jeremy, I have a vague memory of your saying there was some recent issue with tf-job -- could this be related?  @jlewi

**Comment by jlewi** [comment] 2018-11-26 16:14
@amygdala Only issues I'm aware of are RBAC and IAM.

@IronPan might know more.

**Comment by jlewi** [comment] 2018-12-03 15:13
@IronPan @vicaire Any update on this?

**Comment by vicaire** [comment] 2018-12-07 21:36
@qimingj @gaoning777, could you please have a look?

**Comment by jlewi** [comment] 2018-12-17 14:17
@qimingj @gaoning777 any update on this?

**Comment by IronPan** [comment] 2019-01-01 23:00
The RBAC issue should be resolved with the latest version. 
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/pipeline/pipeline-apiserver.libsonnet#L322

@lluunn Could you give another try and if issue still persist, could you share me the pipeline definition and the kubeflow version?

**Comment by jlewi** [comment] 2019-01-07 01:32
@IronPan Is there a pipelines test that covers firing off TFJob from pipelines? If not can we open up an issue to add such at test and use that to verify the fix is working?

**Comment by qimingj** [comment] 2019-01-07 01:40
We currently don't have any samples covering tf-job except for @amygdala's sample. The sample's trainer container (gcr.io/google-samples/ml-pipeline-kubeflow-tf-taxi) was contributed by Amy and is out of pipeline's repo either. 

@amygdala, does your sample still work in latest kubeflow deployment?

I am up for covering tf-job since this is the key component in Kubeflow.

**Comment by amygdala** [comment] 2019-01-07 21:14
Barbara reported that there is a credentials issue (see below) with running my tf-job step in her setup, which was created using the launcher (in contrast to my original instructions, in which I created the GKE cluster nodes with `cloud-platform` scope, then ran the `bootstrapper.yaml`). 
I'm about to try to repro. 
She reports that the issue is NOT fixed by adding that gcp credentials wrapper to the step, but it might be a clusterrole binding issue.  

(I remember that previously, there was some situation where I needed to run:
`kubectl create clusterrolebinding sa-admin --clusterrole=cluster-admin --serviceaccount=kubeflow:pipeline-runner`
to fix something, but I can't remember the context.)

![image](https://user-images.githubusercontent.com/115093/50793702-dc6f3b80-127d-11e9-8782-81fcd80d743a.png)

**Comment by amygdala** [comment] 2019-01-14 18:02
Update part 1: I had no problems with tf-job using a cluster created with 'cloud-platform' scoped nodes and this pipelines bootstrapper: gcr.io/ml-pipeline/bootstrapper:0.1.7 .
So this suggests that it's some credentials/scope setup issue rather than some recent release change, which I wanted to rule out first.

Next I'll play around with a launcher-created cluster. Maybe it needs some additional cluster role during setup.

**Comment by IronPan** [comment] 2019-01-14 19:18
I think the issue is caused by tf-job pod failed to talk to gcp services because tf-job pod doesn't have right GCP service account set up in launcher.
https://github.com/kubeflow/pipelines/blob/df635af4099af67e5aae317f2d6794e058eb1279/components/kubeflow/launcher/src/launch_tf_job.py#L52

We need to mount the kubeflow-user GCP service account here.

**Comment by amygdala** [comment] 2019-01-14 19:34
You're probably right.

**Comment by vicaire** [comment] 2019-03-26 03:40
Closing this issue as a duplicate of #677

**Closed by vicaire** 2019-03-26 03:40 UTC
Labels: priority/p1
