### ISSUE TITLE
Return dict from lightweight python component

### ISSUE THREAD

**Issue by parthmishra** [kubeflow/pipelines#3221] opened 2020-03-05 19:18 UTC
Not sure if this is a bug or intended, but if I try to create a lightweight python component like so:

```python
def dump_dict() -> "dict"
    d = {"k":  "v"}
    return d
```
This fails to be serialized, but if I do a named tuple, it does work: 

```python
def dump_dict() -> NamedTuple("out", [("d", "dict")])
    d = {"k": "v"}
    return d
```

**Comment by parthmishra** [comment] 2020-03-10 17:35
Possibly related, but how do you retain the types of values such as `int` or `bool` when passing a dict? e.g. 

```python
@func_to_container_op
def print_op(d: "dict"):
    for k, v in d.items():
        print(k, type(v)) # always outputs k <class 'str'>

@dsl.pipeline(name="foo")
def pipeline():
   print_op({"k": 2}) 
```

**Comment by Ark-kun** [comment] 2020-03-11 09:46
I've tried the snippets, but the issue does not reproduce - the produced components have equivalent code.

```python
from typing import NamedTuple
from kfp.components import create_component_from_func

def dump_dict1() -> "dict":
    d = {"k":  "v"}
    return d

def dump_dict2() -> NamedTuple("out", [("d", "dict")]):
    d = {"k":  "v"}
    return d

comp1 = create_component_from_func(dump_dict1, output_component_file='dict1.component.yaml')
comp2 = create_component_from_func(dump_dict2, output_component_file='dict2.component.yaml')
```

I think the issue you have is a bit different and caused by a bug related to returning a single collection output. I'm fixing that bug now.
Your second component which is based on `NamedTuple` has incorrect return value. It should be a tuple: `return (d,)`.
The first component is correct from python perspective, but won't work until I fix the bug. A workaround for now is to use the `NamedTuple` syntax to return collections.

**Comment by Ark-kun** [comment] 2020-04-06 21:56
Fixed by https://github.com/kubeflow/pipelines/issues/3262

**Closed by Ark-kun** 2020-04-06 21:56 UTC
Labels: area/sdk, kind/bug, status/triaged
