### ISSUE TITLE
Our ksonnet sometimes throws "SIGSEGV: segmentation violation" failing deployment

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#241] opened 2018-11-13 23:00 UTC
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/232/presubmit-e2e-test-gce-minikube/129/

KSonnet issue: https://github.com/ksonnet/ksonnet/issues/883
Resolved in https://github.com/ksonnet/ksonnet-lib/releases/tag/v0.1.12

```
deploy-ml-pipeline:	Configure ksonnet ...
deploy-ml-pipeline:	Configure ksonnet completed successfully
deploy-ml-pipeline:	Initialize a ksonnet APP ...
deploy-ml-pipeline:	level=info msg="Using context \"default\" from kubeconfig file \"/root/.kube/config\""
deploy-ml-pipeline:	level=info msg="Creating environment \"default\" with namespace \"default\", pointing to cluster at address \"https://10.96.0.1:443\""
deploy-ml-pipeline:	panic: runtime error: invalid memory address or nil pointer dereference
deploy-ml-pipeline:	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x456452]
deploy-ml-pipeline:	goroutine 1 [running]:
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet.parsePaths(0xc4206d0800, 0x6, 0x1, 0xc)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/paths.go:33 +0x1f1
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet.NewCatalog(0xc4206d0800, 0xc420874d90, 0x1, 0x1, 0x40, 0x0, 0x0)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/catalog.go:76 +0x1de
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet.GenerateLib(0xc4213ce030, 0xe, 0x0, 0x0, 0x0)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/ksonnet.go:25 +0xce
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/util/kslib.astBuilder(0xc4213ce030, 0xe, 0xc420cde000, 0x3f0dc0, 0x3ffe00, 0x0, 0x0, 0x0)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/util/kslib/ksonnet.go:87 +0x40
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/util/kslib.Ksonnet(0xc420cde000, 0x3f0dc0, 0x3ffe00, 0x0, 0x0, 0x0)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/util/kslib/ksonnet.go:83 +0x3fd
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/lib.(*Manager).GenerateLibData(0xc4200a08c0, 0x1, 0x1dc69a0, 0x2a15f78)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/lib/lib.go:83 +0x8a
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/app.updateLibData(0x1dc69a0, 0x2a15f78, 0xc4214b6780, 0xf, 0xc421317380, 0x14, 0x1, 0xc421575288, 0x43b4ab, 0xc421660848, ...)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/app/app.go:128 +0xba
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/app.(*App010).AddEnvironment(0xc42000c380, 0x187146a, 0x7, 0xc4214b6780, 0xf, 0xc4204e9e00, 0x0, 0x1a4, 0x0)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/app/app010.go:62 +0x427
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/env.(*creator).Create(0xc42034f830, 0xc42034f830, 0x200)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/env/create.go:117 +0x979
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/env.Create(0x1dcb1a0, 0xc42000c380, 0xc420646bc0, 0x15, 0x187146a, 0x7, 0x187146a, 0x7, 0xc4214b6780, 0xf, ...)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/env/create.go:42 +0x157
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/appinit.(*initApp).Run(0xc420875980, 0x7fd8937ca000, 0x0)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/appinit/init.go:88 +0x452
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/appinit.Init(0x1dc69a0, 0x2a15f78, 0x7fff81075c7f, 0xf, 0xc42020d920, 0x10, 0x0, 0x0, 0xc4214b6780, 0xf, ...)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/appinit/init.go:33 +0x14a
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/actions.(*Init).Run(0xc42034e090, 0xc42034e090, 0x0)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/actions/init.go:106 +0x121
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/actions.RunInit(0xc4212945a0, 0xc420229cb0, 0xe)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/actions/init.go:37 +0x5c
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/clicmd.runAction(0xe, 0xc4212945a0, 0x188a651, 0x17)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/clicmd/actions.go:113 +0x66
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/pkg/clicmd.glob..func17(0x29d5da0, 0xc42075e410, 0x1, 0x1, 0x0, 0x0)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/pkg/clicmd/init.go:107 +0x743
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).execute(0x29d5da0, 0xc42075e3e0, 0x1, 0x1, 0x29d5da0, 0xc42075e3e0)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:753 +0x468
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x29d96a0, 0x13, 0x18b9332, 0x30)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:843 +0x30a
deploy-ml-pipeline:	github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra.(*Command).Execute(0x29d96a0, 0xc420040118, 0x0)
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/vendor/github.com/spf13/cobra/command.go:791 +0x2b
deploy-ml-pipeline:	main.main()
deploy-ml-pipeline:		/Users/bryan/go/src/github.com/ksonnet/ksonnet/cmd/ks/main.go:35 +0x85
deploy-ml-pipeline:	Initialized ksonnet APP completed successfully
```

**Comment by eLco** [comment] 2018-11-14 15:50
Maybe it is possible to add ksonnet flags like --api-spec for example to bootstraper image flags to have more freedom.

**Comment by jinchihe** [comment] 2019-03-20 09:14
I also met the problem today, and that can be reproduced 100%, the deployment has been blocked. 

```
Initializing KSonnet app...
+ echo 'Initializing KSonnet app...'
+ ks init tf-serving-app
level=info msg="Using context \"kubeflow\" from kubeconfig file \"/root/.kube/config\""
level=info msg="Creating environment \"default\" with namespace \"default\", pointing to \"version:v1.12.4\" cluster at address \"
https://kubernetes.default
\""
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x456452]
```

From the https://github.com/ksonnet/ksonnet/issues/883, seems the problem has been fixed in the ks v0.13.1. I think we need to upgrade ks in deployer component.

**Comment by vicaire** [comment] 2019-03-27 01:18
Assuming that this has been resolved since it has been idle for a long time. Please re-open if it is not the case.

**Comment by jinchihe** [comment] 2019-03-27 01:51
@vicaire I met the problem recently, and block the following steps. I created one PR #1005 to fix this, but has not merged yet. Thanks.

**Comment by vicaire** [comment] 2019-03-27 04:22
Thanks @jinchihe. Apologies for closing this.

**Closed** 2019-03-27 05:14 UTC
Labels: area/deployment, help wanted, kind/bug, priority/p0
