### ISSUE TITLE
Experiment Run status became unknown

### ISSUE THREAD

**Issue by shawnho1018** [kubeflow/pipelines#4972] opened 2021-01-11 10:44 UTC
### What steps did you take:
1. I was installing kubeflow 1.2 with Dex on kubernetes cluster, following [this tutorial](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/). 
2. I tested pipeline deployment using [this tutorial](https://github.com/kubeflow/pipelines/blob/b604c6171244cc1cd80bfdc46248eaebf5f985d6/samples/tutorials/Data%20passing%20in%20python%20components/Data%20passing%20in%20python%20components%20-%20Files.py).
### What happened:
The entire deployment was successful on the day when kubeflow was setup. All pipelines pods and kubeflow UI are behaved correctly. 
However, in the following day (I suspect my SSO expired), even though I swapped a valid token, the experiment run UI always show the status is unknown. However, all pods are executed successfully when pipeline is deployed. 

### What did you expect to happen:
The experiment run UI should display correctly
### Environment:
kubeflow 1.2
GKE: 1.18.12

How did you deploy Kubeflow Pipelines (KFP)?
I deploy it along with kubeflow installation. 

KFP version: 
Version: 1.0.4

KFP SDK version: 
kfp                      1.3.0
kfp-pipeline-spec        0.1.3.1
kfp-server-api           1.3.0

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by rastislavs** [comment] 2021-01-22 12:21
We can see the same issue with Kubeflow 1.2 with Dex on Kubernetes. Everything works fine after the first authentication attempt:

![image](https://user-images.githubusercontent.com/15926980/105490034-757e1d00-5cb4-11eb-8bc9-f1829e0ddf78.png)

I could even log out and log in again and it would still work.
Then, few hours later, after re-authentication, the same pipeline is not correctly shown in the UI:

![image](https://user-images.githubusercontent.com/15926980/105490095-934b8200-5cb4-11eb-99bd-37a0dc67862a.png)

**Comment by TrubadurOsman** [comment] 2021-01-22 16:52
I have a similar issue with kubeflow 1.2 Dex. When I create a run, the status becomes unknown, and It stucks.

**Comment by marziman** [comment] 2021-01-22 18:42
@DavidSpek we have the same issue: KFv1.2, K8s 1.17 installation kfctl v1.2 and Dex Multiauth.
The Experiments UI is broken and says"status unknown", even if we clean pods from hand it still doesnt get the update infos in UI.

Could you please help or anyone an idea?
Thx!

**Comment by Bobgy** [comment] 2021-01-23 01:52
Hi @all, can you try https://github.com/kubeflow/pipelines/issues/3763#issuecomment-628379351 to verify if this is a duplicate of that issue?

**Comment by Bobgy** [comment] 2021-01-23 01:53
/cc @yanniszark 
Because this only happens in istio-dex installation, can you take a look?

**Comment by philwinder** [comment] 2021-03-18 13:00
Still happens for me too, using dex. https://github.com/kubeflow/pipelines/issues/3763#issuecomment-628379351 worked for me. So this indicates some kind of race issue.

**Comment by DavidSpek** [comment] 2021-03-18 13:24
@Bobgy I think “istio-dex” might just be synonymous for multi-user installations, it might not be directly related to Dex.

**Comment by Bobgy** [comment] 2021-03-19 05:38
Duplicate of https://github.com/kubeflow/pipelines/issues/3763

**Comment by Bobgy** [comment] 2021-03-19 05:38
Let's concentrate discussion on the canonical issue then

**Closed** 2021-03-19 05:39 UTC
Labels: kind/bug, priority/p0
