### ISSUE TITLE
[UI] Artifacts and Executions Page Loading forever

### ISSUE THREAD

**Issue by lzuwei** [kubeflow/pipelines#3372] opened 2020-03-26 03:52 UTC
### What steps did you take:
Create many runs and artifacts (> 10k)

### What happened:
When the number of executions and artifacts are large (> 10k), the pages takes increasing long to load. From the inspection of network logs, I see over 5k (sometimes 10k) concurrent requests made to GetEventsByArtifactID which can potentially return a large amount of data.

### What did you expect to happen:
Artifacts and Execution pages to load within seconds for browsing.

### Environment:
AWS EKS

How did you deploy Kubeflow Pipelines (KFP)?

Using Kustomize based on https://github.com/e2fyi/kubeflow-aws for AWS EKS

KFP version: 
0.2.4

KFP SDK version: 
0.2.4

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
<img width="1434" alt="Screenshot 2020-03-26 at 11 49 56 AM" src="https://user-images.githubusercontent.com/3502540/77608436-25c9aa80-6f58-11ea-90a0-33929f905e3b.png">

/kind bug

**Comment by Bobgy** [comment] 2020-04-15 05:47
Unfortunately, metadata server doesn't support pagination yet. After it's done, we can work on https://github.com/kubeflow/pipelines/issues/3226.

In the mean time, do you think new feature in https://github.com/kubeflow/pipelines/pull/3457 will help your use case of viewing ml metadata?

**Comment by Bobgy** [comment] 2020-04-15 05:48
This is a duplicate of #3226.
/close
@lzuwei Can you please continue the discussion in #3226? thanks!

**Closed by Bobgy** 2020-04-15 05:48 UTC
Labels: area/frontend, kind/bug
