### ISSUE TITLE
 upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by mmuppidi** [kubeflow/pipelines#1770] opened 2019-08-08 13:08 UTC
**What happened:**
When you try to call KFP api as shown below
```
from kfp import Client

HOST='*****'
CLOUD_IAP_CLIENT_ID='*****'

client = Client(
    host=HOST,
    client_id=CLOUD_IAP_CLIENT_ID
)

config = {}
client.run_pipeline(
        experiment_id='someid',
        job_name='somejob',
        pipeline_package_path='path/to/pipeline/package',
        params=config
)

```
I get this error, which is similar to issue raised by @SinaChavoshi [here](https://github.com/kubeflow/pipelines/issues/908) for UI

```  File "/usr/local/lib/python3.6/dist-packages/kfp/_client.py", line 298, in run_pipeline
    response = self._run_api.create_run(body=run_body)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api/run_service_api.py", line 151, in create_run
    (data) = self.create_run_with_http_info(body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api/run_service_api.py", line 228, in create_run_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/api_client.py", line 373, in request
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/rest.py", line 275, in POST
    body=body)
  File "/usr/local/lib/python3.6/dist-packages/kfp_server_api/rest.py", line 228, in request
    raise ApiException(http_resp=r)
kfp_server_api.rest.ApiException: (503)
Reason: Service Unavailable
HTTP response headers: HTTPHeaderDict({'content-length': '57', 'content-type': 'text/plain', 'date': 'Thu, 08 Aug 2019 12:51:27 GMT', 'server': 'envoy', 'Via': '1.1 google', 'Alt-Svc': 'clear'})
HTTP response body: upstream connect error or disconnect/reset before headers
```
I can make the call If I retry manually multiple times, but that is not expected behavior. If this is because of the expired IAP session then the client should be able to deal with it.

**Comment by Ark-kun** [comment] 2019-08-12 21:20
>I get this error, which is similar to issue raised by @SinaChavoshi [here](https://github.com/kubeflow/pipelines/issues/908) for UI

Yes, this is the same issue.

**Comment by hongye-sun** [comment] 2019-08-12 21:25
Duplicate of #908 

@mmuppidi, let's keep discussion in #908. I think the right fix is to add retry strategy to the client code.

**Comment by hongye-sun** [comment] 2019-08-12 21:27
Duplicate of #908

**Closed by hongye-sun** 2019-08-12 21:27 UTC
Labels: area/sdk/client, priority/p1
