### ISSUE TITLE
ISTIO 1.6+ support in KFP

### ISSUE THREAD

**Issue by jlewi** [kubeflow/pipelines#4698] opened 2020-10-30 15:16 UTC
From @Bobgy in kubeflow/kubeflow#5313

> I think from KFP side, we are relying on istio RBAC heavily for multi-user mode. We won't have bandwidth to upgrade to istio 1.6 if we need migration there within current release schedule for Kubeflow 1.2

Marking as P1 as I think ISTIO 1.4 is pretty old at this point so I suspect this will become a blocker for folks if its not already.

Uber ISTIO 1.6 issue kubeflow/kubeflow#5313

/cc @kubeflow/wg-pipeline-leads

**Comment by Bobgy** [comment] 2020-12-23 05:39
Duplicate of #4768

**Closed by Bobgy** 2020-12-23 05:39 UTC
Labels: priority/p1
