### ISSUE TITLE
[backend] pipeline unable to submit after changing variable

### ISSUE THREAD

**Issue by honghan-wong** [kubeflow/pipelines#10033] opened 2023-09-26 03:12 UTC
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Charmed Kubeflow v1.7

*  KFP version: 
2.0.0-alpha.7

*  KFP SDK version: 
kfp                      2.1.3
kfp-pipeline-spec        0.2.2
kfp-server-api           2.0.1

### Steps to reproduce
By using the following snippet, I can upload the pipeline after compiled.
`python3 test-pipeline.py`

```python
from kfp import dsl
from kfp import compiler
from math_utils import add_numbers

@dsl.component(base_image='python:3.7',
               target_image='gcr.io/my-project/my-component:v1')
def add(num1: int, num2: int) -> int:
    return add_numbers(num1, num2)

@dsl.pipeline
def addition_pipeline(a: int, b: int) -> int:
    add_task_1 = add(num1=a, num2=b)
    add_task_2 = add(num1=add_task_1.output, num2=a)
    return add_task_2.output

compiler.Compiler().compile(pipeline_func=addition_pipeline, package_path='pipeline-add.yaml')
```
However by swapping the variable in `addition_pipeline`, `a` and `b` to `x` and `y`. The kubeflow will throw error below:
```
{"error_message":"Error creating pipeline: Create pipeline failed: InvalidInputError: unknown template format: pipeline spec is invalid","error_details":"Error creating pipeline: Create pipeline failed: InvalidInputError: unknown template format: pipeline spec is invalid"}
```
The problematic code snippet
```python
from kfp import dsl
from kfp import compiler
from math_utils import add_numbers

@dsl.component(base_image='python:3.7',
               target_image='gcr.io/my-project/my-component:v1')
def add(num1: int, num2: int) -> int:
    return add_numbers(num1, num2)

@dsl.pipeline
def addition_pipeline(x: int, y: int) -> int:
    add_task_1 = add(num1=x, num2=y)
    add_task_2 = add(num1=add_task_1.output, num2=x)
    return add_task_2.output

compiler.Compiler().compile(pipeline_func=addition_pipeline, package_path='pipeline-add.yaml')
```

### Expected result

After changing the variable, the pipeline backend should be able to accept the new pipeline.

### Materials and Reference

I followed the official document to try the pipeline.
https://www.kubeflow.org/docs/components/pipelines/v2/components/containerized-python-components/

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment] 2023-10-05 22:43
This is a dupe of https://github.com/kubeflow/pipelines/issues/9451, it was fixed and released in kfp 2.0.0, which will soon in included in Kubeflow 1.8 release.

**Closed by chensun** 2023-10-05 22:43 UTC
Labels: kind/bug, area/backend
