### ISSUE TITLE
Error regarding syncing workflow

### ISSUE THREAD

**Issue by abimur-123** [kubeflow/pipelines#869] opened 2019-02-27 17:03 UTC
Hi all!

I've been playing with Kubeflow and noticed that once my pipelines completed the `ml-persistence-agent` pod continued spewing out the following error at a regular intervals -
```
time="2019-02-27T16:32:26Z" level=error msg="Permanent failure while syncing resource 
(kubeflow/calculation-pipeline-grqzn): CustomError (code: 1): Syncing Workflow (calculation-pipeline-
grqzn): permanent failure: CustomError (code: 1): Error while reporting workflow resource (code: 
InvalidArgument, message: Report workflow failed.: Invalid input error: Failed to update run 
ce4322d1-3a11-11e9-8c52-0a58ac1f1417. Row not found.): rpc error: code = InvalidArgument desc = 
Report workflow failed.: Invalid input error: Failed to update run 
ce4322d1-3a11-11e9-8c52-0a58ac1f1417. Row not found., &{TypeMeta:{Kind: APIVersion:} 
ObjectMeta:{Name:calculation-pipeline-grqzn GenerateName:calculation-pipeline- 
Namespace:kubeflow 
```

I exceeded my logzio limit for the day and these errors are a significant portion of them. Any help regarding this error or ways to suppress these logs would be helpful

**Comment by vicaire** [comment] 2019-03-26 03:44
This should be fixed once we garbage collect the Kubernetes resources (i.e. workflows) that have been terminated. Resolving as a duplicate of https://github.com/kubeflow/pipelines/issues/844

**Closed** 2019-03-26 03:44 UTC
Labels: area/back-end, area/persist-agent, kind/bug
