### ISSUE TITLE
support for building user-supplied component images within pipelines

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/pipelines#1375] opened 2019-05-23 12:10 UTC
Currently if you've got code that has custom dependencies then it needs to go in a component rather than a  ContainerOp or func_to_container_op. This can also make sense if the code is long and complex.

But this is custom code that could change between runs of the pipeline. If the pipeline runs are to fit into a CI/CD setting, then these images need to be rebuilt on each run - or at least every time a change to the repo triggers a run.

Currently you have to do this outside of pipelines. There's a great [example](https://github.com/aronchick/kubeflow-and-mlops) from @aronchick, @berndverst  and @sethjuarez aiming to show a CI/CD integration. In that example a build step is necessary that takes place outside of pipelines - https://github.com/aronchick/kubeflow-and-mlops/blob/master/azure-pipelines.yml#L28. That builds images for pre-processing, training etc. Naturally having to do this outside the pipeline itself undermines portability.

I've been working on an example where the [training image is built inside the pipeline ](https://github.com/ryandawsonuk/pipelines/blob/seldon-examples/samples/seldon/mnist_tf.py#L46) by first [cloning it from git](https://github.com/ryandawsonuk/pipelines/blob/seldon-examples/samples/seldon/mnist_tf.py#L39) and then building with kaniko.

Ideally pipelines would have first-class support for this scenario so that it's clear how to build everything that the pipeline needs within the pipeline. This could be handled through providing examples and I intend to submit a PR for the above. What could be even better would be for DSL to support the option to build an image from a git url, branch and path. These could be set as part of the definition of component or perhaps as parameters to an Op. Then no explicit build steps would be needed in the pipeline's python definition and the necessary preliminary build steps could be inserted into the generated yaml automatically as part of the compilation.

**Comment by Ark-kun** [comment] 2019-05-24 02:10
My vision is to have a good support to do anything using components without having to rely on built-in SDK magic that may be too limited for cases that stray away from the happy path.

It would be great to have some kaniko components that can build an image based on GIT repo.

Hiding the intermediate steps seems to be a less important feature right now. We can try addressing it based on the amount of user feedback.

P.S. While it's nice to do anything as a pipeline, I think there is nothing wrong with having CI/CD where every time someone changes component code, a script is run which builds and pushes a new container image updating the tag. The pipeline can use the images referenced by tag so that the images are always up to date.

P.P.S. Rebuilding the images on the fly every time reduces experiment reproducibility and makes it more fragile. Our CI/CD experience is that GIT pulls fail and Go package installations fail very often.

**Comment by tesla3** [comment] 2019-06-06 07:46
I am seeing this git driven image building has its value. For example to declare explicit dependency of a pipeline step on git repo, we can use git url + commit hash, to frozen so reproducibility won't be an issue  
> P.P.S. Rebuilding the images on the fly every time reduces experiment reproducibility and makes it more fragile.

**Comment by Ark-kun** [comment] 2019-06-21 02:16
The difference between

```
GitContainerOp(
    name='Some name',
    image='base/image',
    git_repo='https://github.com/my_org/project.git',
    git_revision='ac1b...78a1',
    command=[
        '/project/program.py',
        '--param', 'value'
    ],
)
```
and
```
ContainerOp(
    name='Some name',
    image='base/image',
    command=[
        'sh', '-c', 'git clone https://github.com/my_org/project.git -b ac1b...78a1 && "$*"', 
        '/project/program.py',
        '--param', 'value'
    ],
)
```
Seems pretty minimal to me.
The second variant even support Hg and other VCS.

**Comment by Ark-kun** [comment] 2019-10-04 03:19
It might be useful to add a container-building component (e.g. Kaniko-based).
One use case would be to supply image to "launcher-type" components that run it distributed.

**Comment by Ark-kun** [comment] 2019-10-19 00:25
Here is a draft pipeline that builds the container image at runtime inside the pipeline.
https://nbviewer.jupyter.org/github/Ark-kun/pipelines/blob/7c7cdb3/samples/core/build%20images%20in%20pipeline/2019-10-03%20Kaniko%20component.ipynb

And this sample demonstrated building base image containers from a notebook and using them in a component.
https://nbviewer.jupyter.org/github/kubeflow/pipelines/blob/7b6957a/samples/core/component_build/component_build.ipynb

**Comment by ryandawsonuk** [comment] 2019-10-19 06:41
There’s also use of kaniko now in https://github.com/kubeflow/pipelines/blob/master/samples/contrib/seldon/mnist_tf.py#L72

**Comment by ryandawsonuk** [comment] 2019-10-19 06:41
I guess we can close this?

**Comment by Ark-kun** [comment] 2019-10-21 06:23
> There’s also use of kaniko now in https://github.com/kubeflow/pipelines/blob/master/samples/contrib/seldon/mnist_tf.py#L72

Great. For some reason I did not know Kaniko supported local context. That would have made my image building pipeline smaller, easier and more portable.

Thanks.

I'll close this issue when I check in the sample.

**Comment by berndverst** [comment] 2020-03-11 04:16
@ryandawsonuk I assume you use Azure? Either way, take a look at this set of samples which basically uses Kubeflow's Jupyter Notebook server to run a notebook which then uses Kubeflow Fairing and Kaniko in cluster.

https://github.com/kubeflow/examples/tree/master/mnist

In that case a job is launched via TFJob, but you could equally connect to kubeflow pipelines within the cluster.

Create the KFP client (make sure to specify the right namespace) - https://kubeflow-pipelines.readthedocs.io/en/latest/_modules/kfp/_client.html#Client

And then call this:
https://kubeflow-pipelines.readthedocs.io/en/latest/source/kfp.client.html#kfp.Client.run_pipeline

That assumed you previously compiled a pipeline from a DSL and uploaded it through the UI or otherwise created the pipeline.

**Comment by Ark-kun** [comment] 2020-04-16 03:29
Closing the issue since the https://nbviewer.jupyter.org/github/kubeflow/pipelines/blob/7b6957a/samples/core/component_build/component_build.ipynb sample has been checked in.

**Closed by Ark-kun** 2020-04-16 03:29 UTC
Labels: area/sdk, kind/feature
