### ISSUE TITLE
It's not clear that KubeflowRunner().run generates pipeline package somewhere

### ISSUE THREAD

**Issue by hilliao** [kubeflow/pipelines#2475] opened 2019-10-23 21:17 UTC
in [the Jupyter notebook](https://github.com/kubeflow/pipelines/blob/master/samples/core/tfx-oss/TFX%20Example.ipynb), the following line
`run_result = kfp.Client().create_run_from_pipeline_package('chicago_taxi_pipeline_kubeflow.tar.gz', arguments={})` does not say where the .tar.gz file was generated. It should be a full gs:// path with `dsl-compile --py [path/to/python/file] --output [path/to/output/tar.gz]` example command. Otherwise, replace it with `kfp.Client().create_run_from_pipeline_func(pipeline, arguments={})`

**Comment by Ark-kun** [comment] 2019-10-25 01:48
> does not say where the .tar.gz file was generated.

That's because it does not generate that file. This method is for creating a run from a package you already have (e.g. you downloaded it).

Most people should just use the `create_run_from pipeline_func` method. With that method you're doing everything in 1 line. No need to compile anything.

I see how that sample is confusion.
But the source of that confusion is different: 
The real issue is that it's not clear that `KubeflowRunner().run(pipeline)` result in `chicago_taxi_pipeline_kubeflow.tar.gz` being created (and the fact that the name is generated based on the `pipeline_name` parameter of the decorator).

This confusion only exists in the TFX samples which use `tfx.orchestration.kubeflow.runner.KubeflowRunner`.

/cc @neuromage @hongye-sun  @numerology 
Maybe we should improve the API here? E.g. Maybe `KubeflowRunner().run` should actually run the pipeline.

**Comment by neuromage** [comment] 2019-10-25 03:54
As the docs say, `run` compiles and outputs the pipeline file:
https://github.com/tensorflow/tfx/blob/b89024c9f2dfafdef38e3d460000055f53642715/tfx/orchestration/kubeflow/kubeflow_dag_runner.py#L219

It's called `run` due to the fact that the base class defines that as the interface, and other runners actually do run the pipeline. With KFP, it's not possible to trivially run a pipeline (we don't know which cluster you'd like to connect to for the run, for example).

Closing this issue as I don't think there's anything to do here.

**Closed by neuromage** 2019-10-25 03:54 UTC
Labels: area/tfx

**Comment by hilliao** [comment] 2019-10-25 16:28
I found [the wrong pythondoc](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/kubeflow/runner.py). I think by adding comment **chicago_taxi_pipeline_kubeflow.tar.gz** is generated on the _KubeflowRunner().run(pipeline)_ code line would be enough

**Comment by numerology** [comment] 2019-10-25 17:30
> I found [the wrong pythondoc](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/kubeflow/runner.py). I think by adding comment **chicago_taxi_pipeline_kubeflow.tar.gz** is generated on the _KubeflowRunner().run(pipeline)_ code line would be enough

Hi. Your link points to `tfx/tfx/orchestration/kubeflow/runner.py` is that correct?
Would love to correct the doc if that was misleading.

**Comment by hilliao** [comment] 2019-10-25 19:13
@numerology yes, the link pointed to """Deprecated definition of Kubeflow TFX runner.""" which misled me. which doc do you want to correct?

**Comment by numerology** [comment] 2019-10-26 00:47
> @numerology yes, the link pointed to """Deprecated definition of Kubeflow TFX runner.""" which misled me. which doc do you want to correct?

Ah I see. The root cause is that our example is using deprecated KubeflowRunner instead of KubeflowDagRunner. I will fix that shortly.
