### ISSUE TITLE
Need a user interface and/or documentation for the Viewer CRD

### ISSUE THREAD

**Issue by vicaire** [kubeflow/pipelines#1026] opened 2019-03-23 01:59 UTC
We need a user interface and/or documentation for the Viewer CRD:

- So that users can keep track of their instances of Tensorboard or other viewers. 
- So that users do not forget to delete them once they do not need them. 

Ideally, the viewer CRD should automatically terminate processes if they have not been used for a while (though this is harder to do).

**Comment by rileyjbauer** [comment] 2019-03-25 22:44
Is there design work here?
@ajayalfred

**Comment by vicaire** [comment] 2019-03-26 03:04
Yes, there should be design work needed.

**Comment by ajayalfred** [comment] 2019-03-27 01:11
I'll setup a meeting to discuss scope of the design work.

**Comment by rileyjbauer** [comment] 2019-07-17 21:52
@jingzhang36 do you think you can take this on?

**Comment by neuromage** [comment] 2019-07-18 03:43
I think we can close this as a duplicate of https://github.com/kubeflow/kubeflow/issues/3578 which @kimwnasptd has volunteered to tackle.

**Closed by neuromage** 2019-07-18 03:43 UTC
Labels: area/docs, area/front-end, kind/feature, priority/p0
