### ISSUE TITLE
Pipelines UI - history / location bar not working

### ISSUE THREAD

**Issue by strangemonad-faire** [kubeflow/pipelines#1364] opened 2019-05-21 23:28 UTC
Using 0.5 (as installed by the gui 1-click installer)

When you navigate to the pipelines UI from the kubeflow top-level "wrapper" ui you end up with a url like:
`https://my-kubeflow.endpoints.my-gcp-proj.cloud.goog/_/pipeline-dashboard`

The pipeline UI fails to get the correct base uri and never updates the path in the browser's location bar.

Compare this to the bahaviour when you load the pipelines UI "directly" via:
`https://datascience.endpoints.faire-data.cloud.goog/pipeline`

you end up with proper navigation eg:
`https://datascience.endpoints.faire-data.cloud.goog/pipeline/#/pipelines`
`https://datascience.endpoints.faire-data.cloud.goog/pipeline/#/experiments/details/4e3aca19-6614-45ca-94d7-e79e3cdc8a36`

**Comment by ramjinokia** [comment] 2019-05-24 07:12
Hi Shawn, 

Your query :- The pipeline UI fails to get the correct base uri and never updates the path in the browser's location bar.

Yes shawn, you are correct !! Good catch too...
Here they merged few component dashboard like pipeline, Katib, Tj job in single application and also they try to implement in SPA concept. But its not proper SPA implementation and they just using IFrame concept to go another web application internally and maintaining the same routing in browser address bar. 

Please refer the attachment for clear explanation video.
[kubeflowUi-browserurl.zip](https://github.com/kubeflow/pipelines/files/3215546/kubeflowUi-browserurl.zip)


Note :- Single page application (SPA) is a web application that fits on a single page. All your code (JavaScript, HTML, CSS) is retrieved with a single page load. And navigation between pages performed without refreshing the whole page.

**Comment by rileyjbauer** [comment] 2019-07-17 21:48
Closing this as duplicate of #1498

**Closed by rileyjbauer** 2019-07-17 21:48 UTC
Labels: area/front-end, kind/bug, priority/p1
