### ISSUE TITLE
[sdk] Installation of google-ai-platform breaks Pipelines SDK 

### ISSUE THREAD

**Issue by Davidnet** [kubeflow/pipelines#10219] opened 2023-11-08 19:08 UTC
### Environment

*  KFP version:
Vertex AI Pipelines
*  KFP SDK version: 
2.4.0
*  All dependencies version:
kfp                           2.4.0
kfp-pipeline-spec             0.2.2
kfp-server-api                2.0.3

### Steps to reproduce

1. Create a new venv
2. `python -m pip install kfp==2.4.0` 
3. `python -m pip install google-cloud-aiplatform==1.36.0`

Create a new file:

```
import kfp
```

This fails with

#### Stack trace
```
Traceback (most recent call last):
  File "/home/davidnet/Documents/personal/aip_problem/main.py", line 1, in <module>
    import kfp
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/__init__.py", line 40, in <module>
    from kfp import components  # noqa: keep unused import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/components/__init__.py", line 27, in <module>
    from kfp.components.load_yaml_utilities import load_component_from_file
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/components/load_yaml_utilities.py", line 18, in <module>
    from kfp.dsl import structures
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/dsl/__init__.py", line 232, in <module>
    from kfp.dsl.component_decorator import component
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/dsl/component_decorator.py", line 19, in <module>
    from kfp.dsl import component_factory
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/dsl/component_factory.py", line 27, in <module>
    from kfp.dsl import container_component_class
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/dsl/container_component_class.py", line 18, in <module>
    from kfp.dsl import base_component
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/dsl/base_component.py", line 19, in <module>
    from kfp.dsl import pipeline_task
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/dsl/pipeline_task.py", line 26, in <module>
    from kfp.dsl import structures
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/dsl/structures.py", line 34, in <module>
    from kfp.pipeline_spec import pipeline_spec_pb2
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/kfp/pipeline_spec/pipeline_spec_pb2.py", line 38, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/davidnet/Documents/personal/aip_problem/.venv/lib/python3.11/site-packages/google/protobuf/descriptor.py", line 780, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

### Expected result

kfp can be imported without problems

### Materials and Reference

This is also filled in ai-platform repo: [LINK](https://github.com/googleapis/python-aiplatform/issues/2921)

---

Impacted by this bug? Give it a 👍.

**Comment by chensun** [comment] 2023-11-10 00:00
@connor-mccarthy are you aware of any incompatibility between certain versions of KFP SDK and Vertex SDK? Not sure if this is something we need to update on KFP side, or on Vertex SDK side?

**Comment by connor-mccarthy** [comment] 2023-11-10 00:34
@chensun, yes this is a known issue and planned work. Closing as duplicate of https://github.com/kubeflow/pipelines/issues/8370.

**Closed by connor-mccarthy** 2023-11-10 00:34 UTC
Labels: kind/bug, area/sdk
