### ISSUE TITLE
Too many pending pipeline runs overloads the k8s API making it un-responsive

### ISSUE THREAD

**Issue by Helvind** [kubeflow/pipelines#4588] opened 2020-10-06 08:55 UTC
### What steps did you take:
Running around 100 concurrent pipeline runs of a TFX pipeline with 6 steps.

Pipelines are started from a local notebook using the kfp SDK, using `kfp.Client().run_pipelines()`. All steps has explicit resource reqs and limits set by `ContainerOp.set_cpu_limit()` etc.

### What happened:
If the Kubeflow cluster is scaled very low, because of a break in use and the autoscaling has cut it back, All first step pods start out as 'Pending'. The cluster reacts and start to scale, but before it can do this, something starts overloading the k8s APIs to the point where you cannot communicate with the cluster via `kubectl`. The GKE UI reports `repairing cluster` so something is completely dead.

The steps that do get started, runs fine on the compute nodes, untill they need to talk to the meta-data store and die.

The KFP UI becomes unresponsive, or cannot list runs/experiments/pipelines

The `ml-pipeline-scheduledworkflow` reports:
> pkg/mod/k8s.io/client-go@v0.0.0-20180718001006-59698c7d9724/tools/cache/reflector.go:99: Failed to list *v1alpha1.Workflow: Get https://10.92.0.1:443/apis/argoproj.io/v1alpha1/namespaces/kubeflow/workflows?limit=500&resourceVersion=0: dial tcp 10.92.0.1:443: connect: connection refused
> pkg/mod/k8s.io/client-go@v0.0.0-20180718001006-59698c7d9724/tools/cache/reflector.go:99: Failed to list *v1beta1.ScheduledWorkflow: Get https://10.92.0.1:443/apis/kubeflow.org/v1beta1/namespaces/kubeflow/scheduledworkflows?limit=500&resourceVersion=0: dial tcp 10.92.0.1:443: connect: connection refused

The `ml-pipeline-persistenceagent`reports:
> time="2020-10-01T12:26:41Z" level=fatal msg="Error creating ML pipeline API Server client: Failed to initialize pipeline client. Error: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline:8888/apis/v1beta1/healthz: dial tcp: lookup ml-pipeline on 10.92.0.10:53: read udp 10.88.0.15:54856->10.92.0.10:53: read: connection refused: Waiting for ml pipeline API server failed after all attempts.: Get http://ml-pipeline:8888/apis/v1beta1/healthz: dial tcp: lookup ml-pipeline on 10.92.0.10:53: read udp 10.88.0.15:54856->10.92.0.10:53: read: connection refused

### What did you expect to happen:
The pipeline run steps Pending as they should, slowly getting handled

### Environment:

How did you deploy Kubeflow Pipelines (KFP)?
On GKE. Seen both using
- The `kfctl` deployment of full Kubeflow, through the GCP Deployment manager, with meta-data in Minio in cluster
- On a cluster I terraformed before deploying using the GCP Marketplace solution for stand-alone Kubeflow Pipelines, with Cloud SQL backing

KFP version: 
1.0.0

KFP SDK version: 
> kfp                            1.0.1
> kfp-server-api         1.0.1

### Anything else you would like to add:
I have seen some instability when listing large lists of artifacts in the UI, but I think that is something different. It seems to hit the `metadata-grpc-deployment` hard, and of course the different Argo containers. But it seems to be rooted in the failing networking

/kind bug

**Comment by Ark-kun** [comment] 2020-10-06 22:50
@jlewi I think this issue might be relevant to the idea of the CRD-based pipelines API.

**Comment by jlewi** [comment] 2020-10-08 13:46
@Ark-kun What do you think is causing master unavailability and how is that relevant to CRD-based pipelines API?

**Comment by Bobgy** [comment] 2020-10-13 05:59
I've seen KFP users successfully scale to 10000+ runs per day, but I'm not sure how many concurrent runs they are running.
I believe it's too early to conclude CRD is the limitation here. Can we try reproducing a similar scenario and find out why it's breaking down first?

**Comment by rmgogogo** [comment] 2020-10-13 06:25
> @Ark-kun What do you think is causing master unavailability and how is that relevant to CRD-based pipelines API?

It's one of the reason why I always prefer don't use CRD if not necessary.

@Bobgy your fix on the persistence agent helps mitigate the problem? I remember you fixed one in GC phase which would largely reduce the workload to k8s master.

**Comment by Bobgy** [comment] 2020-10-13 06:27
@rmgogogo based on the description, my fix won't help with this case, because the concurrent workflows haven't finished

**Comment by Bobgy** [comment] 2020-10-13 06:28
@Helvind Can you report what was the size of the cluster you saw this problem?

**Comment by Helvind** [comment] 2020-10-13 09:00
@Bobgy Running a GKE cluster with teo nodepools with n1-standard-1 (1 core, 3,5GB mem) and n1-standard-4 (4 core, 15GB mem) machines. I think the errors above occured, when only 1 of the larger nodes was running, and the smaller scaled to 0.

Just for context, the same cluster is currently scaled to 7 small machines and 5 large, and has run nearly 500 seperate pipeline steps in the last 2 hours, so when the compute is there, everything works flawlessly

**Comment by Bobgy** [comment] 2020-10-14 07:25
@Helvind for clarification, did you deploy a regional cluster?
Regional clusters have only one api server, so e.g. when cluster scaling, the single api server may have a downtime, because GCP needs to switch to a larger api server which can handle more workload. I suspect that's the cause for api server downtime.

So for production setup, we always recommend regional clusters, even if you only want to deploy all workloads to one region.

**Comment by Bobgy** [comment] 2020-10-14 07:28
Another potential config we should expose is https://github.com/kubeflow/pipelines/blob/ccc763fb718569a21b95a107ffe5beb023334742/backend/src/agent/persistence/main.go#L86.
The resync period defaults to 30s, all workflows will be re-fetched from k8s api server every 30 seconds. If there are many concurrent workflows in the cluster, we should configure it to a much larger value.

**Comment by Helvind** [comment] 2020-10-14 07:48
@Bobgy 
> So for production setup, we always recommend regional clusters, even if you only want to deploy all workloads to one region.

I am currently only in europe-west4-a, so that might be the problem. Will try to spin up a regional cluster

**Comment by Bobgy** [comment] 2021-01-17 00:39
The question seems answered

**Closed by Bobgy** 2021-01-17 00:39 UTC
Labels: area/perf, kind/bug, priority/p1
