### ISSUE TITLE
Error: "Sorry, /notebook/kubeflow/kfp-notebook is not a valid page"

### ISSUE THREAD

**Issue by Ark-kun** [kubeflow/pipelines#1442] opened 2019-06-04 18:59 UTC
I've deployed KFP 0.1.20 with IAP using web deployer.
I've created a notebook using the Kubeflow UI.
WHen I click "Connect" I'm redirected to the  https://foo.endpoints.bar.cloud.goog/notebook/kubeflow/kfp-notebook page which shows "Sorry, /notebook/kubeflow/kfp-notebook is not a valid page".

![image](https://user-images.githubusercontent.com/1829149/58906122-1541fe00-86c0-11e9-9d3a-a9c956fbb720.png)

**Comment by rileyjbauer** [comment] 2019-06-06 19:40
Has anyone else seen this? When I started a new KFP 0.1.20 deployment on a new cluster, I did not encounter this issue

**Comment by Edilmo** [comment] 2019-06-06 23:04
I have the same issue. I have try with different names and also deleting the PVC generated before to retry.
The output of kubectl -n kubeflow get notebooks in my case is showing the list of running notebooks:
```
git:(master) kubectl -n kubeflow get notebooks
NAME      AGE
daniela   23d
edi       5h
hillary   25d
isabel    3d
lino      25d
miguel    22d
```
The kubernetes cluster is ok from a resource perspective and there is no pods with error or pending state.
The cluster have almost a month working without problems. I'm experiencing the issue since yesterday.
Kubernetes version 1.12 deployed in GCP.
Kubeflow build version 0.5.0

Any advice?

**Comment by fabito** [comment] 2019-06-19 11:26
Having the same issue here. I'm using port forward in the meantime.

These are the entries of the Ambassador Router Table:

URL	| Service | Weight
------------ | ------------- | -------------
http://localhost:8877/tensorboard/ tensorboard/ | tensorboard.kubeflow:9000 | 100.0%
http://localhost:8877/ambassador/v0/check_ready	| 127.0.0.1:8877 | 100.0%
http://localhost:8877/ambassador/v0/check_alive | 127.0.0.1:8877 | 100.0%
http://localhost:8877/ambassador/v0/ | 127.0.0.1:8877 | 100.0%
http://localhost:8877/pipeline |	ml-pipeline-ui.kubeflow |	100.0%
http://localhost:8877/jupyter/ |	jupyter-web-app.kubeflow |	100.0%
http://localhost:8877/tfjobs/ |	tf-job-dashboard.kubeflow |	100.0%
http://localhost:8877/katib/ |	katib-ui.kubeflow |	100.0%
http://localhost:8877/argo/ |	argo-ui.kubeflow |	100.0%
http://localhost:8877/data |	ml-pipeline-ui.kubeflow |	100.0%
http://localhost:8877/ |	centraldashboard.kubeflow |	100.0%

Shouldn't we see a entry for `/notebook/kubeflow` ?

The Ambassador annotation for the notebook service is there:

```bash
# kubectl -n kubeflow describe service/chameleon-client

Name:              chameleon-client
Namespace:         kubeflow
Labels:            <none>
Annotations:       getambassador.io/config:
                     ---
                     apiVersion: ambassador/v0
                     kind:  Mapping
                     name: notebook_kubeflow_chameleon-client_mapping
                     prefix: /notebook/kubeflow/chameleon-client
                     rewrite: /notebook/kubeflow/chameleon-client
                     timeout_ms: 300000
                     service: chameleon-client.kubeflow
                     use_websocket: true
Selector:          statefulset=chameleon-client
Type:              ClusterIP
IP:                10.27.252.89
Port:              <unset>  80/TCP
TargetPort:        8888/TCP
Endpoints:         10.24.3.2:8888
Session Affinity:  None
Events:            <none>
```

But seems like Ambassador haven't detected it.

**Comment by fabito** [comment] 2019-06-19 11:40
Forcing Ambassador to restart solved the issue.
See: https://github.com/kubeflow/kubeflow/issues/3414#issuecomment-499964564

**Comment by Ark-kun** [comment] 2019-06-25 08:28
I have an issue:
My first notebook works fine, but notebooks spawned later are not accessible.

**Comment by aarthipa** [comment] 2020-03-09 08:40
Hi - I see the same error on latest version v1.0.0. Unlike the previous versions, i can restart the Ambassador pods either :(

**Comment by ankitsingi** [comment] 2020-05-05 11:37
Stuck with same issue. Any help ?

**Comment by ConverJens** [comment] 2020-05-07 09:36
Same here. Using KF 1.0.2 which also doesn't use Ambassador anymore.

**Comment by ConverJens** [comment] 2020-05-15 11:16
Bump this

**Comment by ConverJens** [comment] 2020-05-25 06:21
@Ark-kun Any news on this?

**Comment by ConverJens** [comment] 2020-05-27 11:16
@Ark-kun @aarthipa @ankitsingi In the issue linked in my previous comment @jlewi helped me debug this and as he pointed out, the issue was a missing virtualservice. This should have been created by the notebook-controller but it wasn't. Still not sure why that is. So workaround if you only have a very limited number of notebook servers is to manually deploy a virtualservice for each notebook server.

**Comment by ConverJens** [comment] 2020-05-27 11:37
@Ark-kun @jlewi Found the issue, for some reason the USE_ISTIO var was set to false. This seems a bit weird since it is set to false in notebook-controller/base/param.env but it's set to true in notebook-controller/overlays/istio/param.env. Maybe it's caused by some faulty Kustomize setup.
Anyway, setting USE_ISTIO=true in notebook-controller/base/param.env fixed this for me for all notebooks.

**Comment by jlewi** [comment] 2020-05-29 14:56
Closing this issue. Original issue is no longer relevant since it predates ISTIO.

**Closed by jlewi** 2020-05-29 14:56 UTC
Labels: area/kfctl, kind/bug, priority/p0
