### ISSUE TITLE
ui-metadata fail to show up on UI

### ISSUE THREAD

**Issue by HongHuangNeu** [kubeflow/pipelines#3819] opened 2020-05-22 07:29 UTC
### What steps did you take:
[A clear and concise description of what the bug is.]
The  artifact UI fails to display my inline markdown file. The json definition is as follows:  
`{"outputs": [{"storage": "inline", "source": "# TEST AUC:xxxxxx \n\n#GBDT AUC:xxxxxxx", "type": "markdown"}]}` 
The file location is 
`/mlpipeline-ui-metadata.json`

However, after the execution completes successfully, the inline markdown does not show up anywhere, and 'Run output' reports 'No output artifacts found for this run.'
### What happened:
The defined UI elements do not show up on UI
### What did you expect to happen:
defined UI elements are properly displayed
### Environment:
How did you deploy Kubeflow Pipelines (KFP)?
KFP version: 
kubeflow 1.0
KFP SDK version: 
kfp 0.5.1
kfp-server-api 0.5.0
### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
/kind bug
/area sdk

**Comment by Ark-kun** [comment] 2020-05-22 07:33
Does your component have an output with the 'mlpipeline_ui_metadata' name?

How did you create your component?

**Comment by HongHuangNeu** [comment] 2020-05-22 07:36
I used dsl.ContainerOp to create my component. Here are my outputs
` file_outputs={'mlpipeline-metrics': '/mlpipeline-metrics.json',
                               'mlpipeline-ui-metadata': '/mlpipeline-ui-metadata.json'}`

Well, do I need an underscore for the attribute name?

**Comment by HongHuangNeu** [comment] 2020-05-22 07:58
Unfortunately, I change 'mlpipeline-ui-metadata' to 'mlpipeline_ui_metadata' and still 'No output artifacts found for this run.'

**Comment by Ark-kun** [comment] 2020-05-22 09:05
What do you see on the Inputs/Outputs UX tab?

**Comment by Ark-kun** [comment] 2020-05-22 09:12
The issue does not reproduce for me:

```
from typing import NamedTuple
import kfp
from kfp.components import create_component_from_func

@create_component_from_func
def produce_markdown() -> NamedTuple('Outputs', [('MLPipeline_UI_metadata', 'UI_metadata')]):
    import json
    markdown = {"outputs": [{"storage": "inline", "source": "# TEST AUC:xxxxxx \n\n#GBDT AUC:xxxxxxx", "type": "markdown"}]}
    return [json.dumps(markdown)]

def my_pipeline():
    produce_markdown()

kfp_endpoint=None
kfp.Client(host=kfp_endpoint).create_run_from_pipeline_func(my_pipeline, arguments={})
```

![image](https://user-images.githubusercontent.com/1829149/82651590-33ef1c80-9bd1-11ea-8aa8-788687e5646d.png)


component.yaml version also worked:
```
from kfp.components import load_component_from_text

produce_markdown2 = load_component_from_text(
'''
name: Produce Markdown 2
outputs:
- name: MLPipeline_UI_metadata
implementation:
  container:
    image: alpine
    command:
    - sh
    - -c
    - |
      output_metadata_path="$0"
      mkdir -p "$(dirname "$output_metadata_path")"
      echo '
          {
            "outputs" : [{
              "storage": "inline",
              "source": "# TEST AUC:xxxxxx \\n\\n#GBDT AUC:xxxxxxx",
              "type": "markdown"
            }]
          }
      ' >"$output_metadata_path"
    - {outputPath: MLPipeline_UI_metadata}
'''
)

def my_pipeline():
    produce_markdown2()

kfp_endpoint=None
kfp.Client(host=kfp_endpoint).create_run_from_pipeline_func(my_pipeline, arguments={})
```

P.S.
>I used dsl.ContainerOp to create my component.

We strongly advice our users to use `component.yaml` format to describe components instead of `ContainerOp`.

**Comment by HongHuangNeu** [comment] 2020-05-22 10:07
![kubeflow](https://user-images.githubusercontent.com/5564376/82656717-cf76a080-9c56-11ea-87e3-538ea2325dac.png)

I only see that the json files are uploaded to minio,but nothing is displayed except the metrics.
I used the build from Feb,28,2020. Wondering if that is the issue.

**Comment by HongHuangNeu** [comment] 2020-05-22 10:10
![k1](https://user-images.githubusercontent.com/5564376/82657076-4f046f80-9c57-11ea-9dbb-071951af8962.png)

I only see that the two  json files are uploaded, but not markdown displayed.
I use the build from Feb,28,2020. Wondering if that is the issue.

**Comment by Ark-kun** [comment] 2020-05-22 19:06
>I only see that the two json files are uploaded

Looks good.
What's on the "Artifacts" tab?

Can you please try the examples I posted so that we can rule-out some causes?

**Comment by HongHuangNeu** [comment] 2020-05-23 09:51
There are no markdowns or charts displayed on  'Artifacts' tab. I will share the images once I am in the office.

**Comment by HongHuangNeu** [comment] 2020-05-25 02:09
![企业微信截图_15903723707301](https://user-images.githubusercontent.com/5564376/82771786-bac12500-9e6f-11ea-996c-00b6c4ed7199.png)
![企业微信截图_15903724619141](https://user-images.githubusercontent.com/5564376/82771794-c0b70600-9e6f-11ea-97d3-05099995cdf5.png)

Here are the screenshot of the tabs

**Comment by HongHuangNeu** [comment] 2020-05-25 02:16
both metrics and ui-metadata are successfully uploaded, but only metrics are displayed.

**Comment by Ark-kun** [comment] 2020-05-25 07:38
I remember there was some bug with visualizations, but it seems to be fixed in the current KFP version available with Marketplace and Standalone deployments (0.5.1). I missed the backend version in your first post.

**Comment by HongHuangNeu** [comment] 2020-05-25 07:54
Could you give me the related issue? Are there any workaround for visualization? Just any way to render documents or web pages on Kubeflow pipeline UI would be fine.

**Comment by Bobgy** [comment] 2020-05-26 08:07
@HongHuangNeu Can you open developer tools (usually F12 in browser) first and see if there are any error messages when switching to artifact output page?
Also, can you click the `ml-pipeline-ui-metadata` artifact and check if content is the same as you wrote.

**Comment by HongHuangNeu** [comment] 2020-05-26 09:55
Yes, here are the error messages:

![error](https://user-images.githubusercontent.com/5564376/82886993-ecbeae00-9f79-11ea-8fc8-7747bb883473.png)

**Comment by HongHuangNeu** [comment] 2020-05-26 10:19
We found the cause: we configure another minio instance for our kubeflow pipeline installation. Somewhere in the pipeline still refer to the default minio installation when fetching the metadata, which causes this bug.

**Comment by Bobgy** [comment] 2020-05-26 11:03
You need to override ml-pipeline-ui's MINIO_SERVICE_HOST and MINIO_SERVICE_PORT env vars to let It point to  the right one.
@HongHuangNeu

**Comment by tarjintor** [comment] 2020-05-26 11:57
> 
> 
> You need to override ml-pipeline-ui's MINIO_SERVICE_HOST and MINIO_SERVICE_PORT env vars to let It point to the right one.
> 

hello,I face the same issue
I want to know how can I know I can use these env var to change the ml-pipeline-ui to point to the right one,
I try to inspect the image of gcr.io/ml-pipeline/frontend ,and only env I find are:
 ```
           "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=12.14.1",
                "YARN_VERSION=1.21.1",
                "API_SERVER_ADDRESS=http://localhost:3001"
            ],

```
@Bobgy 
Maybe the only way is to read source code?

**Comment by Bobgy** [comment] 2020-05-27 00:42
@tarjintor Yes, you are right. So far, they are only documented in source code. Contributions welcomed.

**Comment by Bobgy** [comment] 2020-05-27 01:11
/close
Closing the issue as question has been troubleshooted and answered.
If you think adding related documentation is very helpful, please file a separate issue. Thanks!

**Closed by Bobgy** 2020-05-27 01:11 UTC
Labels: area/frontend, area/sdk, kind/question, status/triaged
