### ISSUE TITLE
TypeError while uploading a pipeline with SDK

### ISSUE THREAD

**Issue by eedorenko** [kubeflow/pipelines#3441] opened 2020-04-04 00:11 UTC
### What steps did you take:
Invoke the following code:
```python
client = kfp.Client(host=host, namespace=namespace)
pipeline_file = os.path.join(pipeline_file_path)
pipeline = client.pipeline_uploads.upload_pipeline(pipeline_file, name=pipeline_name)
```

### What happened:
Got an error:
Traceback (most recent call last):
  File "/Users/efedorenko/work/kubeflow-play/code/publish_pipeline.py", line 13, in <module>
    pipeline = client.pipeline_uploads.upload_pipeline(pipeline_file, name=pipeline_name)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 55, in upload_pipeline
    (data) = self.upload_pipeline_with_http_info(uploadfile, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api/pipeline_upload_service_api.py", line 135, in upload_pipeline_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 169, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 241, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 626, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 280, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 626, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 278, in __deserialize
    return self.__deserialize_datatime(data)
  File "/usr/local/lib/python3.7/site-packages/kfp_server_api/api_client.py", line 592, in __deserialize_datatime
    return parse(string)            
  File "/usr/local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1358, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 722, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/usr/local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/usr/local/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not dict

**However**, the pipeline has been uploaded

### What did you expect to happen:
The thing is that in the generated *api_pipeline_version.py* 'swagger_types.created_at' has 'datetime', but in response it is returned as {"seconds": 122131431}. If I change the type to 'object', it works fine.

### Environment:

KFP version: Build commit: ca58b22

KFP SDK version: 0.3.0

/kind bug

**Comment by elikatsis** [comment] 2020-04-06 12:20
This is duplicate of https://github.com/kubeflow/pipelines/issues/2764 which is fixed for KFP >= 0.2.1.

Unfortunately, it's not a client but a backend issue, so you will have to either upgrade your deployment or use `kfp-server-api==0.1.18.3` which seems to not produce this issue [with any limitation that this may come with].

**Comment by eedorenko** [comment] 2020-04-06 19:51
Kubeflow (including pipelines) has been installed following this guide https://www.kubeflow.org/docs/azure/deploy/install-kubeflow/
So https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.1.yaml has been applied. So, do I need to apply something on top of it?

**Comment by eedorenko** [comment] 2020-04-07 16:44
According to the [Kubeflow application matrix](https://www.kubeflow.org/docs/reference/version-policy/#kubeflow-application-matrix) the default KFP versions coming with Kubeflow v1.0.1 is 0.2.0. The question is if Kubeflow v1.0.1 works with KFP and can I just upgrade it with 
```
 export PIPELINE_VERSION=<version-you-want-to-upgrade-to>
 kubectl apply -k github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=$PIPELINE_VERSION
```
as it is described here https://www.kubeflow.org/docs/pipelines/installation/standalone-deployment/#upgrading-kubeflow-pipelines

**Comment by eedorenko** [comment] 2020-04-07 17:01
I tried it, it didn't work:

for: "github.com/kubeflow/pipelines/manifests/kustomize/env/dev?ref=0.3.0": Deployment.apps "mysql" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"mysql", "application-crd-id":"kubeflow-pipelines"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Comment by jonasdebeukelaer** [comment] 2020-04-09 11:46
@eedorenko if you're still looking to upgrade pipelines in your kubeflow install, I managed to do that today: https://github.com/kubeflow/pipelines/issues/2237#issuecomment-611484454

**Comment by Bobgy** [comment] 2020-04-15 06:54
FYI, there were some recent efforts to upgrade KFP to 0.2.5 in Kubeflow 1.0.2.
If you want to upgrade manually, you can refer to manifests there: https://github.com/kubeflow/manifests/issues/984

/close
closing this because it's a version problem

**Closed by Bobgy** 2020-04-15 06:54 UTC
Labels: kind/bug
