### ISSUE TITLE
XGBoost pipeline failed

### ISSUE THREAD

**Issue by xiaohanhuang** [kubeflow/pipelines#3222] opened 2020-03-05 23:54 UTC
### What steps did you take:
Create a run with example XGBoost pipeline but failed first step

### What happened:
Here is the log:

INFO:googleapiclient.discovery:URL being requested: GET 
https://www.googleapis.com/discovery/v1/apis/dataproc/v1/rest
INFO:root:Fetching latest pod metadata: xgboost-trainer-2bcw7-3224152408.
INFO:root:Start KFP context with ID: 2e7d9a2b5a83c0bdc5de0ae5ebb64432.
INFO:root:Cluster Details: 
https://console.cloud.google.com/dataproc/clusters/xgb-1782e77f-47d1-4273-8b7f-1267b8abac6d?project=xxxx&region=us-central1
INFO:googleapiclient.discovery:URL being requested: POST 
https://dataproc.googleapis.com/v1/projects/xxxx/regions/us-central1/clusters?alt=json&requestId=2e7d9a2b5a83c0bdc5de0ae5ebb64432
INFO:googleapiclient.discovery:URL being requested: GET 
https://dataproc.googleapis.com/v1/projects/xxxx/regions/us-central1/operations/0584e2b1-0557-3797-8b5f-c2f33bab71a3?alt=json
INFO:root:Operation projects/xxxx/regions/us-central1/operations/0584e2b1-0557-3797-8b5f-c2f33bab71a3 is not done. Wait for 30s.
INFO:googleapiclient.discovery:URL being requested: GET 
https://dataproc.googleapis.com/v1/projects/xxxx/regions/us-central1/operations/0584e2b1-0557-3797-8b5f-c2f33bab71a3?alt=json
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ml/kfp_component/launcher/__main__.py", line 45, in <module>
    main()
  File "/ml/kfp_component/launcher/__main__.py", line 42, in main
    launch(args.file_or_module, args.args)
  File "kfp_component/launcher/launcher.py", line 45, in launch
    return fire.Fire(module, command=args, name=module.__name__)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python2.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "kfp_component/google/dataproc/_create_cluster.py", line 74, in create_cluster
    wait_interval)
  File "kfp_component/google/dataproc/_create_cluster.py", line 89, in _create_cluster_internal
    return _dump_cluster(operation.get('response'))
  File "kfp_component/google/dataproc/_create_cluster.py", line 109, in _dump_cluster
    cluster.get('clusterName'))
AttributeError: 'NoneType' object has no attribute 'get'

The exitHandler actually delete the cluster succesfully:

INFO:googleapiclient.discovery:URL being requested: GET 
https://www.googleapis.com/discovery/v1/apis/dataproc/v1/rest
INFO:root:Fetching latest pod metadata: xgboost-trainer-2bcw7-80709960.
INFO:root:Start KFP context with ID: d1cf16a75ad5ffe7e902e4f5fbb36a40.
INFO:googleapiclient.discovery:URL being requested: DELETE 
https://dataproc.googleapis.com/v1/projects/xxxx/regions/us-central1/clusters/xgb-1782e77f-47d1-4273-8b7f-1267b8abac6d?alt=json&requestId=d1cf16a75ad5ffe7e902e4f5fbb36a40
INFO:googleapiclient.discovery:URL being requested: GET 
https://dataproc.googleapis.com/v1/projects/xxxx/regions/us-central1/operations/576ba8c3-7053-3447-8266-2e87e4b3070e?alt=json
INFO:root:Operation projects/xxxx/regions/us-central1/operations/576ba8c3-7053-3447-8266-2e87e4b3070e is not done. Wait for 30s.
INFO:googleapiclient.discovery:URL being requested: GET 
https://dataproc.googleapis.com/v1/projects/xxxx/regions/us-central1/operations/576ba8c3-7053-3447-8266-2e87e4b3070e?alt=json
metadata: {"status": {"state": "DONE", "stateStartTime": "2020-03-05T23:17:17.817Z", "innerState": "DONE"}, "clusterUuid": "73496807-8473-4395-bf4b-2220a098ebfc", "description": "Delete cluster", "clusterName": "xgb-1782e77f-47d1-4273-8b7f-1267b8abac6d", "operationType": "DELETE", "statusHistory": [{"state": "PENDING", "stateStartTime": "2020-03-05T23:17:17.116Z"}, {"state": "RUNNING", "stateStartTime": "2020-03-05T23:17:17.152Z"}], "@type": "type.googleapis.com/google.cloud.dataproc.v1.ClusterOperationMetadata"}
done:     true
response: {"@type": "type.googleapis.com/google.protobuf.Empty"}
name:     projects/xxxx/regions/us-central1/operations/576ba8c3-7053-3447-8266-2e87e4b3070e

### What did you expect to happen:
run without error
### Environment:

GKE
How did you deploy Kubeflow Pipelines (KFP)?

Using the manifest deploy in existing cluster, istio option

KFP version: 
1.0? Used latest kfctl 1.0 for deployment
KFP SDK version: 
1.0? Used latest kfctl 1.0 for deployment

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment] 2020-03-10 04:06
Is this a duplicate of https://github.com/kubeflow/kubeflow/issues/4803?

Did you deploy this to GCP? Maybe you need to check https://www.kubeflow.org/docs/gke/pipelines/authentication-pipelines/.

**Comment by xiaohanhuang** [comment] 2020-03-11 23:28
> Is this a duplicate of [kubeflow/kubeflow#4803](https://github.com/kubeflow/kubeflow/issues/4803)?
> 
> Did you deploy this to GCP? Maybe you need to check https://www.kubeflow.org/docs/gke/pipelines/authentication-pipelines/.

Yes, it was on deployed in an existing GKE cluster with https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_k8s_istio.v1.0.0.yaml

From the doc you provide, "You don’t need to do anything. Full Kubeflow deployment has already deployed the user-gcp-sa secret for you." Did I miss anything?

**Comment by Bobgy** [comment] 2020-03-12 07:34
@xiaohanhuang Thanks for pointing out the problem. The doc is a little outdated, that statement was true in KF 0.7, but I need to adjust it for KF 1.0.

**Comment by Bobgy** [comment] 2020-03-12 07:35
TODO: update https://www.kubeflow.org/docs/gke/pipelines/authentication-pipelines/ with new recommendation for Kubeflow 1.0.

**Comment by xiaohanhuang** [comment] 2020-03-12 17:07
> @xiaohanhuang Thanks for pointing out the problem. The doc is a little outdated, that statement was true in KF 0.7, but I need to adjust it for KF 1.0.

Could you provide some instruction what need to be done to get it work?

**Comment by Bobgy** [comment] 2020-03-13 03:39
@xiaohanhuang You can refer to my answer in https://github.com/kubeflow/pipelines/issues/3069#issuecomment-595043632

**Comment by rmgogogo** [comment] 2020-03-18 05:44
Seems duplicated issue. answered in #3069. Here close but feel free to reopen.

**Closed by rmgogogo** 2020-03-18 05:45 UTC
Labels: area/deployment/kubeflow, kind/bug
