### ISSUE TITLE
Kubeflow / AI Platform Pipelines runtime context missing when output is taken from cache

### ISSUE THREAD

**Issue by SaschaHeyer** [kubeflow/pipelines#5303] opened 2021-03-15 13:10 UTC
### What steps did you take:

1. deploy pipeline with one component
2. run pipeline with one component (👍 works)
3. add another component
4. run the pipeline (this time the output is taken from cache) (👎 fails)

### What happened:
The pipeline runs into the following error 
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 198, in launch
    self._exec_properties)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 167, in _run_driver
    component_info=self._component_info)
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/components/base/base_driver.py", line 270, in pre_execution
    driver_args, pipeline_info)
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/components/base/base_driver.py", line 158, in resolve_input_artifacts
    producer_component_id=input_channel.producer_component_id)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/metadata.py", line 948, in search_artifacts
    pipeline_info)
RuntimeError: Pipeline run context for PipelineInfo(pipeline_name: sentiment4, pipeline_root: gs://sascha-playground-doit-kubeflowpipelines-default/sentiment4, run_id: sentiment4-qnknl) does not exist
```
Assume the second component doesn't find the cached data because the component did not exist in the first run.

First run:
<img width="1216" alt="1run" src="https://user-images.githubusercontent.com/1991664/111158263-1e9c1200-8598-11eb-969f-370aec9c4be2.png">

Second run with additional component
<img width="1216" alt="2run" src="https://user-images.githubusercontent.com/1991664/111158281-22c82f80-8598-11eb-8e2a-ec3b070163f0.png">

### What did you expect to happen:
Pipeline run completes without errors

### Environment:
AI Platform Pipelines

How did you deploy Kubeflow Pipelines (KFP)?
AI Platform Pipelines

KFP version: https://github.com/kubeflow/pipelines/commit/d79071c0bef19442483abc101769a0d893e72f42

KFP SDK version: no pip in AI Platform Pipelines

### Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]

/kind bug

**Comment by Bobgy** [comment] 2021-03-27 00:56
Hi @SaschaHeyer, thank you for the report!

What is your TFX version? KFP cache shouldn't run on TFX pipelines. This is a bug.

**Comment by SaschaHeyer** [comment] 2021-03-29 10:05
Hi @Bobgy 
issue can be reproduced with 0.27.0 and 0.28.0

**Comment by Bobgy** [comment] 2021-03-30 07:32
@SaschaHeyer can you provide a minimum reproducible TFX pipeline with a requirements.txt for all dependencies versions?
I tried TFX 0.28.0 with KFP 1.5.0-rc.0 (which should be very similar to 1.4.1 you tested on), and cannot reproduce this problem.

**Comment by SaschaHeyer** [comment] 2021-04-07 07:12
Hi @Bobgy 
here is the example you can use https://github.com/SaschaHeyer/Sentiment-Analysis-TFX

**Comment by Bobgy** [comment] 2021-04-09 11:06
Thank you! I will try it out today

**Comment by Bobgy** [comment] 2021-04-19 03:16
Hi @SaschaHeyer, sorry I do not know how to compile and run your pipeline.
Can you document that?

**Comment by Bobgy** [comment] 2021-04-19 03:27
An important thing to verify is whether the following annotation exists on your pods:
![image](https://user-images.githubusercontent.com/4957653/115177640-379d6300-a102-11eb-8d61-b756b431b098.png)

`pipelines.kubeflow.org/pipeline-sdk-type: tfx`

**Comment by judyliou** [comment] 2021-05-06 13:49
@Bobgy I have the same issue, and I have the annotation `pipelines.kubeflow.org/pipeline-sdk-type: tfx` on my pods.
Could you explain how this annotation affect if it exists?

**Comment by Bobgy** [comment] 2021-05-20 04:28
@judyliou sorry for the late reply, the annotation is used to distinguish tfx pipelines from KFP pipelines.
For TFX pipelines, they should not be cached by KFP cache controller, because TFX come with their first party caching feature. This bug is caused by KFP caching TFX pipelines.

Can you confirm your KFP backend is upgraded to 1.5.0+? The fix was released in 1.5.0, see https://github.com/kubeflow/pipelines/pull/5188.

**Comment by Bobgy** [comment] 2021-05-20 04:30
Ohh, so that explains this original issue, KFP backend is 1.4.1 and the fix was only released in 1.5.0

**Comment by Bobgy** [comment] 2021-05-29 00:44
@axeltidemann one workaround is to upgrade cache server after install 

```
# 1. connect to cluster kubectl

kubectl edit deployment cache-server -n namespace

# edit the image tag to 1.5.0
```

**Comment by aneeshc-c** [comment] 2021-05-31 08:40
@Bobgy That would not work. Google Marketplace does not have any container images with a version 1.5.0 tag, you can check that [here](https://console.cloud.google.com/gcr/images/cloud-marketplace/GLOBAL/google-cloud-ai-platform/kubeflow-pipelines/cacheserver?gcrImageListsize=30).

**Comment by Bobgy** [comment] 2021-05-31 09:51
@aneeshc-c you are right, I fixed the instruction to use oss image repo instead

**Comment by axeltidemann** [comment] 2021-05-31 12:49
That did not bring back visualisations, @Bobgy . Any other suggestions?

**Comment by Bobgy** [comment] 2021-05-31 23:39
@axeltidemann can you report your ML Metadata tab screenshot after the fix? (And it should be a new run too)

**Comment by axeltidemann** [comment] 2021-06-01 07:03
Sure, @Bobgy. You can tell that the Outputs are wrong, it should be Type **ExampleStatistics**.
![Screenshot 2021-06-01 at 08 58 45](https://user-images.githubusercontent.com/6352118/120280202-aea84880-c2b7-11eb-8c46-e79eb9aa6ac5.png)

**Comment by Bobgy** [comment] 2021-06-01 07:45
@axeltidemann thanks for the extra info, that reminded me https://github.com/kubeflow/pipelines/pull/5364 fix is also required. (the metadata you showed are logged from KFP metadata-writer, but we should show metadata of native TFX pipelines).

Refer to https://www.kubeflow.org/docs/components/pipelines/installation/overview/#choosing-an-installation-option, I'd suggest deploying Kubeflow Pipelines standalone 1.6.0 to get all the fixes.

**Comment by axeltidemann** [comment] 2021-06-01 16:14
Thank you for that suggestion, @Bobgy. We are a bit hesitant to not use the Google Marketplace one. But thanks for letting us know we should wait for 1.6.0.

**Comment by Bobgy** [comment] 2021-06-07 12:13
I'm curious why, but I'm working on blockers to release 1.6.0. Rough ETA would be 2 weeks

**Comment by axeltidemann** [comment] 2021-06-07 13:25
@Bobgy roughly 2 weeks to get 1.6.0 on Google Marketplace? That is great!

**Comment by AlirezaSadeghi** [comment] 2021-06-24 19:16
@Bobgy We also have the standalone pipeline installation through Google Cloud Marketplace, now I'm wondering what's the proper upgrade strategy? We have had 3 clusters so far, `0.4`, `1.0` and `1.4`, and everytime `upgrade` for us has been:
* Go through the market place installation
* Create a new cluster and install the newer version 
* Try to deprecate the older one and migrate pipelines into the newer one

1. Is there anyway to `upgrade` instead of `fresh re-install` from the Marketplace package?
2. Considering there's no way to `upgrade` from Market place, do you recommend us follow the manual upgrade docs [here](https://www.kubeflow.org/docs/components/pipelines/installation/standalone-deployment/#upgrading-kubeflow-pipelines) for gcp market place installations or the same `install and migrate` strategy?

**Comment by Bobgy** [comment] 2021-07-14 03:53
@AlirezaSadeghi did you read the docs: https://www.kubeflow.org/docs/distributions/gke/pipelines/upgrade/?

**Comment by Bobgy** [comment] 2021-07-14 03:55
Regarding this issue, I also just learned that tfx templates may override to use `tfx-template` as label value: https://github.com/tensorflow/tfx/blob/985105d58d04292163fd1e25d51a319d32448b9a/tfx/experimental/templates/penguin/kubeflow_runner.py#L66.

So KFP should match loosely, any label value with the word tfx should be ignored by KFP cacher and metadata-writer.

**Closed** 2021-07-14 05:24 UTC
Labels: kind/bug
