### ISSUE TITLE
Any plan to integrate with Tekton pipeline

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/pipelines#951] opened 2019-03-11 02:42 UTC
[Tekton pipeline](https://github.com/tektoncd/pipeline) plan to be a k8s-native piepline resource, so any plan for kubeflow pipeline integrate with it?

/cc @jlewi @jinchihe @hougangliu

**Comment by vicaire** [comment] 2019-03-26 04:12
Thanks @gyliu513. This is a very interesting proposal. We need to compare the feature set with Argo. I am not sure that it would make sense to support two pipeline resources if the feature set if similar. What do you think?

**Comment by gyliu513** [comment] 2019-03-26 06:46
@vicaire Seems the goal of https://github.com/tektoncd/pipeline is to build a K8s-native Pipeline resource, tekton pipeline is also a project of CDF https://cd.foundation/ , so the tekton pipeline seems deserve to check more ;-)

**Comment by vicaire** [comment] 2019-03-27 03:52
Sounds good. We will have a look at Tekton.

**Comment by Ark-kun** [comment] 2019-03-27 20:26
Tekton is focusing on CI/CD scenarios while Argo and KF Pipelines have bigger scope and are more general-purpose.

**Comment by missedone** [comment] 2019-07-11 08:10
@Ark-kun , would like to share a little more of the bigger scope of KF/Argo, i'm evaluating tekton/KF/Argo for our next continuous deployment tool.

**Comment by animeshsingh** [comment] 2019-08-05 16:20
@vicaire Tekton is becoming the CI/CD backbone behind our cloud and even in OpenShift. Would like to see if you have given this more thought, and this might also be an opportunity to decouple KFP from Argo to some extent

**Comment by axsaucedo** [comment] 2019-08-12 16:54
@animeshsingh we are currently exploring Tekton at Seldon as well, still early stages but I would be interested to learn more about how you are using it internally. Furthermore, I personally see there is may be some ambiguity on when it comes towards defining CI/CD vs ETL logic within individual KF Pipelines. I think it would be interesting to explore even a conceptual separation between the use of KF Pipelines for ETL (ML Training / Batch processing) vs the CI/CD of trained pipelines. I agree that having yet another service added to the KF Package is not desired, but exploring Tekton pipelines itself and even decoupling KFP from Argo could provide interesting insights on this conceptual separation of ETL vs CI/CD. What are your thoughts on this?

**Comment by jlewi** [comment] 2019-11-26 14:40
@axsaucedo @animeshsingh I thought someone at the MLOps Sig meeting someone mentioned that they were working on a KFP DSL compiler that would execute on Tekton?

Does KFP have a well defined resource model? Would Tekton make a good resource model for pipelines?

**Comment by Ark-kun** [comment] 2019-12-12 22:40
There were some plans to split the DSL compiler in two parts - the first creates a logical pipeline (a pipeline/graph component) and the second stage that converts the graph component to Argo workflow. This would make it easier to support more runners and orchestrators as they only need to implement the second part.

What are the key differences between Argo and Tekton?
Does Tekton help you pass data between tasks? (this is a core feature that Argo supports).

**Comment by jlewi** [comment] 2019-12-13 18:22
Here's my limited understanding of Tekton's model.

* a Task corresponds to a sequence of steps executed sequentially in a pod
* Data can be passed between steps in a pod using the pod volume /workspace
* To pass data between tasks you use  [PipelineResource](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md) which provides a mechanism for moving data into/out of /workspace
    * For example, the git resource basically adds a container to a task which syncs a repo to /workspace so it is available to the steps in your task
    * There is a [PipelineResource for GCS](https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#storage-resource)
    * And an open issue tektoncd/pipeline#323 to support S3

@bobcatfish and other tekton experts might be able to shed more light on Tekton

**Comment by geota** [comment] 2019-12-27 19:02
found a good discussion on tektoncd vs argo
https://github.com/tektoncd/pipeline/issues/644#issuecomment-475032948

> If you are interested we created this spreadsheet a while ago which compares some of the Tekton Pipeline goals with existing CI/CD tools (though it compares Argo, not Argo CI or CD). (note this is shared with members of https://groups.google.com/forum/#!forum/knative-dev - since we used to be part of knative! - you'll have to join the group to see the doc)

**Comment by animeshsingh** [comment] 2020-03-13 17:55
@Ark-kun there is some work going on for kfp-tekton compiler here, curently being driven by us, but we are hoping we can others join in the effort. 

https://github.com/kubeflow/kfp-tekton
http://bit.ly/kfp-tekton

_There were some plans to split the DSL compiler in two parts - the first creates a logical pipeline (a pipeline/graph component) and the second stage that converts the graph component to Argo workflow. This would make it easier to support more runners and orchestrators as they only need to implement the second part._

Any further work on your side? If you want, we should start some internal discussions

cc @jlewi

**Comment by animeshsingh** [comment] 2020-03-24 06:31
@Ark-kun coming back to it. Would be great to syncup on the above cc @jessiezcc

**Comment by jlewi** [comment] 2020-04-29 16:44
Duplicate of #3647

**Closed by jlewi** 2020-04-29 16:44 UTC
Labels: area/wide-impact, kind/misc, priority/p2
