### ISSUE TITLE
"driver: bad connection" when using Managed storage via Google Cloud Marketplace deployment

### ISSUE THREAD

**Issue by Svendegroote91** [kubeflow/pipelines#4973] opened 2021-01-11 10:58 UTC
### What steps did you take:
- Using GCP default VPC network settings
- Created multi-regional EU Google Cloud Storage bucket
- Create mySQL (v5.7) instance in europe-west1-d with only root user and no password (default settings: Public IP - I also tried enabling the private IP but that also did not resolve the issue)
- Configured AI Platform Pipelines (Google's KFP managed service) using Managed Storage
(params: storage bucket name: bucket name (without gs://), sql connection name: connection name copied from the mySQL UI, database prefix: 'db-test-sven', database username & password left empty to default to root user without password.

### What happened:
Deployment hangs on 'ml-pipeline' component that reports `driver: bad connection` as critical and a continuous stream of errors : `[mysql] 2021/01/11 10:52:23 packets.go:36: unexpected EOF`

Also the 'metadata-grpc-deployment' fails to start with following errors:
```
2021-01-11 10:52:07.160738: F ml_metadata/metadata_store/metadata_store_server_main.cc:220] Non-OK-status: status status: Internal: mysql_real_connect failed: errno: 2002, error: Can't connect to MySQL server on 'mysql' (115)MetadataStore cannot be created with the given connection config.
```

```
2021-01-11 10:52:08.781095: F ml_metadata/metadata_store/metadata_store_server_main.cc:220] Non-OK-status: status status: Internal: mysql_real_connect failed: errno: 2013, error: Lost connection to MySQL server at 'handshake: reading inital communication packet', system error: 11MetadataStore cannot be created with the given connection config.
```

It appears the mySQL connection cannot be instantiated, any help on how to resolve this?

### What did you expect to happen:
Deployment to successfully finish.

How did you deploy Kubeflow Pipelines (KFP)?
Google Cloud Marketplace

KFP version: 1.0.4

/kind bug

**Comment by Bobgy** [comment] 2021-01-27 11:37
@Svendegroote91 Sorry for the late reply, reading through your description, it sounds like
> database username & password left empty to default to root user without password.

this part is wrong, you need to type `root` into database username, it's not the default when you leave it to empty.

**Comment by andreclaudino** [comment] 2021-03-11 14:52
I am having exactly the same problem, but I fill the database username as `root`.

The biggest difference is that my cluster is deployed in us-central1.

**Comment by Bobgy** [comment] 2021-03-16 15:35
Hi @andreclaudino, can you try to inspect logs from the cloudsql proxy pod? It should give us more info to identify the root cause

**Comment by yuku** [comment] 2021-04-06 23:07
I had almost same problem (except for resources region)

> can you try to inspect logs from the cloudsql proxy pod?

In my case, I found:

> Cloud SQL Admin API has not been used in project PROJECT_ID before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/sqladmin.googleapis.com/overview?project=PROJECT_ID then retry.

And activating the specified API fixed the problem. Hope this helps.

**Comment by Bobgy** [comment] 2021-04-09 11:04
Closing because problem seems resolved. Feel free to comment if that's not the case

**Closed by Bobgy** 2021-04-09 11:04 UTC
Labels: kind/question
