### ISSUE TITLE
Metadata Writer does not record input parameter values in ML Metadata

### ISSUE THREAD

**Issue by paveldournov** [kubeflow/pipelines#4556] opened 2020-09-28 03:03 UTC
### What steps did you take:
1. Run AutoML Tables pipeline (https://github.com/kubeflow/pipelines/blob/master/samples/core/AutoML%20tables/AutoML%20Tables%20-%20Retail%20product%20stockout%20prediction.ipynb)
2.Navigate to the runtime graph, select any node with inputs
3. Open ML Metadata tab view
4. Look for Inputs

### What happened:
No inputs are recorded in ML MEtadata while the pipeline steps clearly have inputs

### What did you expect to happen:
See the step inputs according to the pipeline definition

### Environment:
KFP 1.0

How did you deploy Kubeflow Pipelines (KFP)?
GCP GKE Marketplace

/kind bug
/area backend
/area sdk

**Comment by Ark-kun** [comment] 2020-09-29 02:49
Hello. Thank you for your report.
This is a known issue. Metadata Writer correctly records the artifacts arguments, but does not record parameter arguments.
This issue affects not just Metadata Writer, but the rest of the KFP UX: The UX does not show all input parameters and when it does, the names are mangled.

The root cause of the issue is the fact that ContainerOp does not have concept of an input.

Consider the following code:
```python
def some_op(num_iterations: int):
    return ContainerOp(
        command=['my_prog.py', num_iterations]
    )

def my_pipeline():
    some_task = some_op(num_iterations=100)
```
When you execute it, you get:
```
some_task == ContainerOp(
    command=['my_prog.py', 100]
)
```

So by the time the task reaches the compiler, it has no information that `100` is not a constant value, but at some point came through a variable called `num_iterations`.

Fortunately, when creating `ContainerOp`s from components (which have concept of inputs), it might be possible to try and preserve the input names. Let me try to fix this issue.

**Comment by Bobgy** [comment] 2020-09-29 10:08
/hold
we should wait for https://github.com/kubeflow/pipelines/pull/4563 to be merged first

**Closed** 2020-10-12 03:32 UTC
Labels: area/backend, area/metadata-writer, area/sdk, kind/bug
