### ISSUE TITLE
Python 3 support in Dataflow component

### ISSUE THREAD

**Issue by TheMichaelHu** [kubeflow/pipelines#2601] opened 2019-11-13 16:02 UTC
Apache beam has had python 3 support since version 2.14.0, and python 2 will reach EOL in January 2020. Right now it looks like using `python2` is hard coded into the [Dataflow component](https://github.com/kubeflow/pipelines/blob/master/components/gcp/container/component_sdk/python/kfp_component/google/dataflow/_launch_python.py):

```python
def _prepare_cmd(project_id, python_file_path, args, staging_location):
    dataflow_args = [
        '--runner', 'dataflow', 
        '--project', project_id]
    if staging_location:
        dataflow_args += ['--staging_location', staging_location, '--temp_location', staging_location]
    return (['python2', '-u', python_file_path] + 
        dataflow_args + args)
```

Can an option be added to run Dataflow jobs using `python3`?

**Comment by aaltay** [comment] 2020-07-06 17:31
/reopen

This issue is still open. Beam and Dataflow will soon stop supporting python2 pipelines. After that, kubeflow may not be able launch Dataflow pipelines.

Also, this might be a duplicate of: https://github.com/kubeflow/kubeflow/issues/4894

**Comment by aaltay** [comment] 2020-10-05 17:01
Friendly ping to keep this open.

Dataflow will support only python3 before the end of the year (very likely starting in October). Beam also EOLed its py2 support and newer Beam versions starting 2.25.0 will be supporting python3 only.

My suggestion is to change:

return (['python2', '-u', python_file_path] + 
        dataflow_args + args)

to use `python3` instead of `python2`. I can make this change but I do not have how this will impact kubeflow users.

**Comment by aaltay** [comment] 2020-10-06 01:52
I started https://github.com/kubeflow/pipelines/pull/4583 to fix this. It only changes "python2" to "python" to allow a user to choose their default python version whether it is py2 or py3. I need some action from the repo owners to run tests on the PR.

**Closed** 2020-10-07 08:34 UTC
Labels: area/components, kind/feature, status/triaged
