### ISSUE TITLE
Unable to use TFJob in Kubeflow Pipeline, current dsl compiler have not support for TFJOBOP

### ISSUE THREAD

**Issue by sivachama** [kubeflow/pipelines#973] opened 2019-03-15 05:45 UTC
Planning to run distributed TFJOb as a stage in Kubeflow pipeline on K8 cluster on azure. When I checked  dslcompiler code, their is no support for TFJobOP. Please suggest if any work around.

**Comment by Ark-kun** [comment] 2019-03-15 20:33
>Planning to run distributed TFJOb as a stage in Kubeflow pipeline on K8 cluster on azure. When I checked dslcompiler code, their is no support for TFJobOP. 

Compiler is not a good place for a TFJob op.
Neither is DSL.
TFJob launcher is a component, that can be used to launch a trainer container.

See https://github.com/kubeflow/pipelines/blob/9511d964d5c46678d4c3fa58cd0ee406182b9ed9/components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py

This comment describes how to pass the launcher and trainer arguments: https://github.com/kubeflow/pipelines/blob/9511d964d5c46678d4c3fa58cd0ee406182b9ed9/components/kubeflow/launcher/src/launch_tf_job.py#L17

**Comment by vicaire** [comment] 2019-03-26 02:03
+1 on the feature request. 

We should make it easy to run a TF-job using pipeline by providing a component.

**Comment by vicaire** [comment] 2019-03-26 03:39
Closing this issue as a duplicate of https://github.com/kubeflow/pipelines/issues/677

**Closed by vicaire** 2019-03-26 03:39 UTC
Labels: area/components, area/sdk/dsl, kind/feature, priority/p1

**Comment by rmgogogo** [comment] 2020-04-28 01:15
For now it can use ResourceOp directly.
TFJob is more for training big models which one machine can't handle, aka distributed training. Cloud Machine Learning Engine (CMLE) can be a better option if it's on GCP.

**Comment by maerory** [comment] 2023-08-22 04:03
> https://github.com/kubeflow/pipelines/blob/9511d964d5c46678d4c3fa58cd0ee406182b9ed9/components/kubeflow/launcher/kubeflow_tfjob_launcher_op.py

What is the purpose of launcher as compared to running the docker container that trains the deep learning model on itself?
