### ISSUE TITLE
Support mutl-platform storage for kaniko

### ISSUE THREAD

**Issue by IronPan** [kubeflow/pipelines#345] opened 2018-11-21 00:35 UTC
Currently kaniko pod mounts the GCP service accounts so it can access to GCP API.

https://github.com/kubeflow/pipelines/pull/343

We should consider make this a configurable setting so people can switch to non GCP stack as they want.

**Comment by IronPan** [comment] 2019-01-09 23:32
see related feature request https://github.com/kubeflow/pipelines/issues/641

**Comment by gaoning777** [comment] 2019-07-30 16:40
duplicate of https://github.com/kubeflow/pipelines/issues/1700

**Closed by gaoning777** 2019-07-30 16:40 UTC
Labels: area/sdk/dsl/compiler, help wanted, kind/feature, platform/other, priority/p1
