### ISSUE TITLE
pipeline parameters,CustomPythonPackageTrainingJobRunOp, NoneType object is not subscriptable

### ISSUE THREAD

**Issue by cah-parita-desai** [kubeflow/pipelines#6503] opened 2021-09-03 07:17 UTC
Hi Sina,

This is not the case.
I am already passing python_module_name as str. 
But still getting the error.

Sample for reference:-

PROJECT_ID = 'xyz'
LOCATION = 'abc'
PIPELINE_ROOT_PATH = 'gs://test'
MODEL_DISPLAY_NAME='custom-test1-template'
PIPELINE_DISPLAY_NAME = 'custom-test-pipeline'
CONTAINER_URI='us-docker.pkg.dev/vertex-ai/training/scikit-learn-cpu.0-23:latest'
STAGING_BUCKET='gs://test1'
BASE_OUTPUT_DIR='gs://test2/custom/'
PYTHON_PACKAGE_GCS_URI='gs://my-bucket/trainer-0.1.tar.gz'
PYTHON_MODULE_NAME='trainer.task'
ENDPOINT_DISPLAY_NAME='custom-pipeline-endpoint'
MODEL_SERVING_CONTAINER_IMAGE_URI='us-docker.pkg.dev/vertex-ai/prediction/sklearn-cpu.0-24:latest'
TRAINING_JOB_NAME='custom-pipeline-job'
REPLICA_COUNT=1
MACHINE_TYPE='n1-standard-4'

def pipeline(
    project: str = PROJECT_ID,
    location: str = LOCATION,
    display_name: str = TRAINING_JOB_NAME,
    python_package_gcs_uri: str = PYTHON_PACKAGE_GCS_URI,
    python_module_name: str = PYTHON_MODULE_NAME,
    container_uri: str = CONTAINER_URI,
    staging_bucket: str = STAGING_BUCKET,
    base_output_dir: str = BASE_OUTPUT_DIR,
    model_serving_container_image_uri: str = MODEL_SERVING_CONTAINER_IMAGE_URI,
    replica_count: int = REPLICA_COUNT,
    machine_type: str =MACHINE_TYPE ,
    model_display_name: str = MODEL_DISPLAY_NAME,
):
       
    training_job_run_op = gcc_aip.CustomPythonPackageTrainingJobRunOp(
            display_name=display_name,
            python_package_gcs_uri=python_package_gcs_uri,
            python_module=python_module_name,
            container_uri=container_uri,
            project=project,
            location=location,
            staging_bucket=staging_bucket,
            base_output_dir=base_output_dir,
            model_serving_container_image_uri=model_serving_container_image_uri,
            replica_count=replica_count,
            machine_type=machine_type,
    )
Note:- I am not able to reopen this issue.

_Originally posted by @cah-parita-desai in https://github.com/kubeflow/pipelines/issues/6426#issuecomment-912281873_

**Comment by zijianjoy** [comment] 2021-09-10 00:33
cc @SinaChavoshi

**Comment by cah-parita-desai** [comment] 2021-09-27 07:42
Getting this error now on changing to python_module_name. Have put the code in #6426 

KeyError                                  Traceback (most recent call last)
<ipython-input-9-57017d2a36e9> in <module>
      2 pip_package_path=PIPELINE_DISPLAY_NAME + ".json"
      3 compiler.Compiler().compile(
----> 4     pipeline_func=pipeline, package_path=pip_package_path
      5 )

/opt/conda/lib/python3.7/site-packages/kfp/v2/compiler/compiler.py in compile(self, pipeline_func, package_path, pipeline_name, pipeline_parameters, type_check)
   1137         pipeline_parameters = {
   1138             param.name: param for param in args_list_with_defaults
-> 1139         }
   1140         # Update pipeline parameters override if there were any.
   1141         pipeline_parameters_override = pipeline_parameters_override or {}

/opt/conda/lib/python3.7/site-packages/kfp/v2/compiler/compiler.py in _create_pipeline_v2(self, pipeline_func, pipeline_name, pipeline_parameters_override)
   1070           pipeline_func: Pipeline function with @dsl.pipeline decorator.
   1071           pipeline_name: The name of the pipeline. Optional.
-> 1072           pipeline_parameters_override: The mapping from parameter names to values.
   1073             Optional.
   1074 

<ipython-input-7-72f66fff9826> in pipeline(project, location, display_name, python_package_gcs_uri, python_module_name, container_uri, staging_bucket, base_output_dir, model_serving_container_image_uri, replica_count, machine_type, model_display_name)
     38             model_serving_container_image_uri=model_serving_container_image_uri,
     39             replica_count=replica_count,
---> 40             machine_type=machine_type,
     41     )
     42 

/opt/conda/lib/python3.7/site-packages/google_cloud_pipeline_components/aiplatform/utils.py in component_yaml_generator(**kwargs)
    531         additional_args = []
    532         for key, args in args_to_serialize.items():
--> 533             for arg_key, value in args.items():
    534                 additional_args.append(f'--{key}.{arg_key}')
    535                 additional_args.append(value)

KeyError: 'python_module_name'

**Comment by SinaChavoshi** [comment] 2021-09-27 15:52
Duplicate of #6426 , I'm closing this issue and reopening the original issue.

**Closed by SinaChavoshi** 2021-09-27 15:52 UTC
