### ISSUE TITLE
Kubeflow-pipeline : dsl-compile: command not found

### ISSUE THREAD

**Issue by vackysh** [kubeflow/pipelines#1351] opened 2019-05-17 10:00 UTC
Hi,

I have created a pipeline and  while compiling it using the below command, it is throwing an error.

kubeflow]$ dsl-compile --py /home/centos/data/SVM_pipeline.py --output /home/ubuntu/data/SVM_pipeline.tar.gz

error:
-bash: dsl-compile: command not found

From documentation, i came to know that dsl-compile comes with SDK package, then why it is getting failed? If it needs to be installed separately, what is the command ?

Regards,
Varun

**Comment by ryandawsonuk** [comment] 2019-05-17 13:08
Here's the page on installing the SDK:

https://www.kubeflow.org/docs/pipelines/sdk/install-sdk/

Hopefully after running through that you'll be able to do `which dsl-compile` and have the command available

**Comment by Ark-kun** [comment] 2019-05-17 21:38
There might be some problem with your python environment. Maybe the dir where the scripts are installed is not in your `PATH`.

It might be easier to just make your pipeline self-compiling by adding 

```
if __name__ == '__main__':
    kfp.compiler.Compiler().compile(my_pipeline, __file__ + '.zip')
```

at the end of the script.

**Comment by vackysh** [comment] 2019-05-20 08:03
Hi @ryandawsonuk ,

Thanks for your reply.

I will be getting a below error while executing the command
"pip install https://storage.googleapis.com/ml-pipeline/release/0.1.20/kfp.tar.gz --upgrade"

Error:

"
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting https://storage.googleapis.com/ml-pipeline/release/0.1.20/kfp.tar.gz
  Using cached https://storage.googleapis.com/ml-pipeline/release/0.1.20/kfp.tar.gz
ERROR: kfp requires Python '>=3.5.3' but the running Python is 2.7.5
"

However, the default is 3.6

python --version
Python 3.6.7

Why the error message is still showing python version 2.7.3 ? How could be come out of this error and let the dsl-complie to be installed ?

**Comment by ryandawsonuk** [comment] 2019-05-20 09:12
You could try using ‘pip3 install’ instead of ‘pip install’. Perhaps you’ve got more than one python on your machine.

**Comment by Ark-kun** [comment] 2019-05-21 22:16
> I will be getting a below error while executing the command
> "pip install https://storage.googleapis.com/ml-pipeline/release/0.1.20/kfp.tar.gz --upgrade"

The release documentation gives a different command: https://github.com/kubeflow/pipelines/releases/tag/0.1.20
```pip3 install https://storage.googleapis.com/ml-pipeline/release/0.1.20/kfp.tar.gz --upgrade```

Have you tried it?

**Comment by Ark-kun** [comment] 2019-05-24 01:46
Closing since the issue is obvious - `pip` program pointing to python2's pip.

This issue is outside of the Pipelines scope and easy to fix.

**Closed by Ark-kun** 2019-05-24 01:46 UTC
