### ISSUE TITLE
Archiving one run from experiment page, archives all runs

### ISSUE THREAD

**Issue by SinaChavoshi** [kubeflow/pipelines#1219] opened 2019-04-24 17:22 UTC
Repro steps: 
1. when to experiments page
2. expanded one of the experiments 
3. selected one of the experiments 
4. clicked archive. 
5. all runs are showing up under archive.  

Also restore did not remove them form archive

https://screenshot.googleplex.com/WyixZPfiFB4

**Comment by rileyjbauer** [comment] 2019-04-24 18:09
I am having trouble reproducing this.
What do you mean when you say "selected one of the experiments"?

**Comment by SinaChavoshi** [comment] 2019-04-24 18:18
sorry meant selected one of the runs

**Comment by rileyjbauer** [comment] 2019-04-24 18:32
It seems to be working for me with a build from near head.

There was an issue with archiving that was resolved not too long ago: #1150 (fixed by #1151)

Do you know if your KFP is new enough to include that change? It'll need to be the newest release, Version 0.1.17

**Comment by SinaChavoshi** [comment] 2019-04-24 18:59
Got it, I'm on an older version that does not have that. I will upgrade and
verify.

**Comment by vicaire** [comment] 2019-05-28 22:26
Closing. Please re-open if this is still an issue.

**Closed** 2019-05-28 22:26 UTC
Labels: area/front-end, kind/bug
