### ISSUE TITLE
Let user choose the version of Tensorboard deployed by UI

### ISSUE THREAD

**Issue by neuromage** [kubeflow/pipelines#2185] opened 2019-09-21 03:49 UTC
We should allow the user to manually customize the version of Tensorboard deployed by the UI, defaulting to latest. This will let them easily get around bugs like that in #2140 

/assign @jingzhang36
 to take a first stab or re-assign as needed.

**Comment by Bobgy** [comment] 2020-01-21 02:06
/close
duplicate of https://github.com/kubeflow/pipelines/issues/2514
and already resolved in https://github.com/kubeflow/pipelines/pull/2690

**Closed by Bobgy** 2020-01-21 02:07 UTC
Labels: area/frontend, priority/p1, status/triaged
